*** empty log message ***
git-svn-id: file:///usr/local/svn/fsc2@6284 934aee4a-8510-0410-ae50-ec5b2ea4bb86

diff --git a/trunk/fsc2/me6x00/utils/me6x00 b/trunk/fsc2/me6x00/utils/me6x00
--- a/trunk/fsc2/me6x00/utils/me6x00
+++ b/trunk/fsc2/me6x00/utils/me6x00
@@ -69,33 +69,39 @@ case "$1" in
 			log_failure_msg "Loading ME6X00 module failed."
 			exit 1
 		fi
-		major=`grep me6x00 /proc/devices | awk '{print $1}'`
+		grep 'devfs=only' /proc/cmdline > /dev/null 2>&1
 		if [ $? != 0 ]; then
-			log_failure_msg "Can't determine major device number for ME6X00 cards."
-			exit 1
-		fi
-		nboards=`grep '1402:6[01][013][48f]' /proc/pci | wc -l`
-		i=0;
-		while [ $i -lt $nboards ]; do
-			mknod /dev/me6x00_$i c $major $i
+			major=`grep me6x00 /proc/devices | awk '{print $1}'`
 			if [ $? != 0 ]; then
-				log_failure_msg "Creating device files for ME6X00 cards failed."
+				log_failure_msg "Can't determine major device number for ME6X00 cards."
 				exit 1
 			fi
-			chmod 666 /dev/me6x00_$i
-			i=$(($i+1))
-		done
+			nboards=`grep '1402:6[01][013][48f]' /proc/pci | wc -l`
+			i=0;
+			while [ $i -lt $nboards ]; do
+				mknod /dev/me6x00_$i c $major $i
+				if [ $? != 0 ]; then
+					log_failure_msg "Creating device files for ME6X00 cards failed."
+					exit 1
+				fi
+				chmod 666 /dev/me6x00_$i
+				i=$(($i+1))
+			done
+		fi
 		test "$2" = "restart" || log_success_msg "Starting ME6X00 support."
 		;;
 
 	 stop)
-		for f in /dev/me6x00_*; do
-			rm -f $f
-			if [ $? != 0 ]; then
-				log_failure_msg "Deleting device files for ME6X00 cards failed."
-				exit 1
-			fi
-		done
+		grep 'devfs=only' /proc/cmdline > /dev/null 2>&1
+		if [ $? != 0 ]; then
+			for f in /dev/me6x00_*; do
+				rm -f $f
+				if [ $? != 0 ]; then
+					log_failure_msg "Deleting device files for ME6X00 cards failed."
+					exit 1
+				fi
+			done
+		fi
 		rmmod me6x00 > /dev/null 2>&1
 		if [ $? != 0 ]; then
 			log_failure_msg "Unloading ME6X00 module failed."
diff --git a/trunk/fsc2/witio_48/utils/witio_48 b/trunk/fsc2/witio_48/utils/witio_48
--- a/trunk/fsc2/witio_48/utils/witio_48
+++ b/trunk/fsc2/witio_48/utils/witio_48
@@ -69,15 +69,18 @@ case "$1" in
 			log_failure_msg "Loading WITIO-48 module failed."
 			exit 1
 		fi
-		major=`grep witio_48 /proc/devices | awk '{print $1}'`
+		grep 'devfs=only' /proc/cmdline > /dev/null 2>&1
 		if [ $? != 0 ]; then
-			log_failure_msg "Can't determine major device number for WITIO-48 cards."
-			exit 1
-		fi
-		mknod -m 666 /dev/witio_48 c $major 0
-		if [ $? != 0 ]; then
-			log_failure_msg "Creating device file for WITIO-48 cards failed."
-			exit 1
+			major=`grep witio_48 /proc/devices | awk '{print $1}'`
+			if [ $? != 0 ]; then
+				log_failure_msg "Can't determine major device number for WITIO-48 cards."
+				exit 1
+			fi
+			mknod -m 666 /dev/witio_48 c $major 0
+			if [ $? != 0 ]; then
+				log_failure_msg "Creating device file for WITIO-48 cards failed."
+				exit 1
+			fi
 		fi
 		test "$2" = "restart" || log_success_msg "Starting WITIO-48 support."
 		;;
@@ -88,10 +91,13 @@ case "$1" in
 			log_failure_msg "Unloading WITIO-48 module failed."
 			exit 1
 		fi
-		rm -f /dev/witio
-			if [ $? != 0 ]; then
-			log_failure_msg "Deleting device files for WITIO-48 cards failed."
-			exit 1
+		grep 'devfs=only' /proc/cmdline > /dev/null 2>&1
+		if [ $? != 0 ]; then
+			rm -f /dev/witio
+				if [ $? != 0 ]; then
+					log_failure_msg "Deleting device files for WITIO-48 cards failed."
+				exit 1
+			fi
 		fi
 		test "$2" = "restart" || log_success_msg "Stopping WITIO-48 support."
 		;;
