Added 2.6 support to MEilhaus driver (me6x00)
git-svn-id: file:///usr/local/svn/fsc2@7869 934aee4a-8510-0410-ae50-ec5b2ea4bb86

diff --git a/trunk/fsc2/me6x00/driver/Makefile b/trunk/fsc2/me6x00/driver/Makefile
--- a/trunk/fsc2/me6x00/driver/Makefile
+++ b/trunk/fsc2/me6x00/driver/Makefile
@@ -23,20 +23,77 @@
 # To contact the author send email to:  jt@toerring.de
 
 
+MODULE   := me6x00.o
+PWD      := $(shell pwd)
+
+
+# Unless the user set the environment variable ME6X00_KERNEL_SOURCE
+# assume that we can find out where the kernel sources are (or at least
+# the kernel headers) from the 'build' symbolic link in the module
+# directory of the currently running kernel. Only if this doesn't exist
+# use '/usr/src/linux/' as a last resort - but it's not unlikely to point
+# to the wrong kernel code or may even not exist...
+
 ifneq ($(ME6X00_KERNEL_SOURCE),)
-    KERNEL_INC = $(ME6X00_KERNEL_SOURCE)
-else
-	KERNEL_INC = $(shell if [ -d /lib/modules/`uname -r`/build ]; then \
-							 echo "/lib/modules/`uname -r`/build"; \
-						 else \
-							 echo "/usr/src/linux"; \
-						 fi )
+    KERNELDIR := $(ME6X00_KERNEL_SOURCE)
 endif
 
-MODULE   = me6x00.o
+KERNELDIR ?= $(shell if [ -d /lib/modules/`uname -r`/build ]; then \
+					     echo "/lib/modules/`uname -r`/build"; \
+					 else \
+						 echo "/usr/src/linux"; \
+					 fi )
+
+# If KERNEL_VER isn't set determine it from the the kernel source directory
+# and then call make again with KERNEL_VER now being set. If KERNEL_VER
+# couldn't be found out that way give up and print an error message
+
+ifndef KERNEL_VER
+
+KERNEL_VER := $(shell grep UTS_RELEASE $(KERNELDIR)/include/linux/version.h \
+				      2>/dev/null | \
+				      sed 's/^[^"]\{1,\}"\([0-9\.]\{1,\}\).*$$/\1/' \
+					  2>/dev/null)
+
+all $(MODULE) install clean:
+	@if [ -z "$(KERNEL_VER)" ]; then \
+		echo "Error: Can't figure out kernel version under the assumption that the kernel sources are at $(KERNELDIR)"; \
+		exit 2; \
+	fi
+	$(MAKE) KERNEL_VER=$(KERNEL_VER) $@
+
+else      # if KERNEL_VER is set
+
+# First handle the case that we're building for a 2.6 kernel
+
+ifeq ($(findstring 2.6,$(KERNEL_VER)),2.6)
+
+ifneq ($(KERNELRELEASE),)    # if can use the kernel build system
+	obj-m := $(MODULE)
+
+else                         # otherwise make kernel build system available
+
+EXTRA_CFLAGS := -I$(PWD)
+
+all:
+	$(MAKE) -C $(KERNELDIR) M=$(PWD) EXTRA_CFLAGS=$(EXTRA_CFLAGS) modules
+
+install:
+	$(MAKE) -C $(KERNELDIR) M=$(PWD) modules_install
+
+clean:
+	$(MAKE) -C $(KERNELDIR) M=$(PWD) clean
+	$(RM) $(RMFLAGS) *~
+
+endif
+
+else
+
+# Otherwise we're dealing with some pre-2.6 kernel (hopefully 2.4)
+
 SOURCES  = me6x00.c
 HEADERS  = pci-compat.h sysdep.h me6x00_drv.h autoconf.h
-INCLUDES = -I$(KERNEL_INC)/include -I.
+INCLUDES = -I$(KERNELDIR)/include -I.
 
 CFLAGS   = -D__KERNEL__ -DMODULE -DLINUX -O2 -Wall -Wstrict-prototypes
 
@@ -74,3 +131,6 @@ cleanup:
 
 clean:
 	$(RM) $(RMFLAGS) *.o autoconf.h *~
+
+endif
+endif
