dkms support for most modules

diff --git a/me6x00/INSTALL b/me6x00/INSTALL
--- a/me6x00/INSTALL
+++ b/me6x00/INSTALL
@@ -30,6 +30,34 @@ function get_reply() {
 
 
 ################################################################
+
+function get_module_conf()
+{
+	if [ -e /etc/modules ]
+	then
+		echo "/etc/modules";
+	elif [ -e /etc/modules.conf ]
+	then
+		echo "/etc/modules.conf"
+	elif [ -e /etc/conf.modules ]
+	then
+		echo "/etc/conf.modules"
+	elif [ -e /etc/modules.conf.local ]
+	then
+	    echo "/etc/modules.conf.local"
+	fi
+}
+
+
+################################################################
+
+function get_major()
+{
+	echo `grep ME6X00_MAJOR driver/autoconf.h | awk '{print $3}'`
+}
+
+
+################################################################
 # Ask the user for the module paramters
 
 function do_setup() {
@@ -311,15 +339,137 @@ please run the command\n\
 ################################################################
 # Does everything needed for the installation
 
-function do_install() {
+function do_install()
+{
+	# Check that user has the necessary permissions for installation
 
-	# Ask user if he wants to install the library, driver and include files etc.
+	if [ `id -u` != "0" ]
+	then
+		dialog --msgbox \
+"For installation you need root privileges.\n\
+Please become root (or run 'INSTALL' with\n\
+'sudo') to continue with the installation.\n" 7 48
+		exit 0;
+	fi
+
+	MAJOR=$(get_major)
+	MODULECONF=$(get_module_conf)
+
+	install_lib
+	install_driver
+	install_device_files
+	install_modules_conf
+	install_init_script
+	update_dep
+	load_module
+}
+
+
+################################################################
+# Installs the library
+
+function install_lib()
+{
+	# Ask user if he wants to install the library
 
 	PREFIX=`grep ME6X00_PREFIX driver/autoconf.h | sed 's/[^\"]*//' | tr -d \"`
-	MAJOR=`grep ME6X00_MAJOR driver/autoconf.h | awk '{print $3}'`;
+
+	dialog --yesno \
+"Do you want to install the library? This involves\n\
+copying the following files, if necessary creating\n\
+directories that don't exist:\n\n\
+ driver/me6x00_drv.h => $PREFIX/include/me6x00_drv.h\n\
+ lib/libme6x00.so    => $PREFIX/lib/libme6x00.so\n\
+ lib/libme6x00.a     => $PREFIX/lib/libme6x00.a\n\
+ lib/me6x00.h        => $PREFIX/include/me6x00.h" 13 74
+
+	test $? -eq 0 || return
+
+	# Do the basic installation (covered by the makefile)
+
+	make install_lib >> makelog 2>&1
+	if [ $? -ne 0 ]
+	then
+		dialog --msgbox \
+"Sorry, installation of libarary failed.\n\
+See \"makelog\" for the reasons.\n" 7 45;
+    	exit 1
+	fi
+}
+
+
+################################################################
+# Installs the kernel module
+
+function install_driver()
+{
+	dkms > /dev/null 2>&1
+	if [ $? -eq 0 ]
+	then
+		dialog --yesno \
+"Do you want to install the device driver using dkms?" 5 60
+        if [ $? -eq 0 ]
+		then
+			install_dkms
+		else
+			install_driver_mech
+		fi
+	else
+		install_driver_mech
+	fi
+}
+
+
+################################################################
+# Installs the kernel module using dkms
+
+function install_dkms()
+{
+	if [ -n "`dkms status -m me6x00 -v 1.0`" ]
+	then
+		dkms uninstall -m me6x00 -v 1.0 -k $KERNEL_VERSION >> makelog 2>&1
+		rm -rf /usr/src/me6x00-1.0 >> makelog 2>&1
+		cp -r driver /usr/src/me6x00-1.0
+	else
+		dkms add driver >> makelog 2>&1
+	fi
+
+	if [ $? -ne 0 ]
+	then
+		dialog --msgbox \
+"Sorry, Failed to add module to dkms.\n\
+See \"makelog\" for the reasons.\n" 7 45;
+        exit 1
+	fi
+
+	dkms build -m me6x00 -v 1.0 -k $KERNEL_VERSION >> makelog 2>&1
+	if [ $? -ne 0 ]
+	then
+"Sorry, Failed to build module with dkms.\n\
+See \"makelog\" for the reasons.\n" 7 45;
+        exit 1
+	fi
+
+	dkms install -m me6x00 -v 1.0 -k $KERNEL_VERSION >> makelog 2>&1
+	if [ $? -ne 0 ]
+	then
+"Sorry, Failed to unstall module with dkms.\n\
+See \"makelog\" for the reasons.\n" 7 45;
+        exit 1
+	fi
+
+	DKMS_INSTALL=1
+}
+
+
+################################################################
+# Installs the kernel module "manually"
+
+function install_driver_mech()
+{
 	if [ $IS_NEW_KERNEL ]
 	then
-		MOD_INST_AS="/lib/modules/$KERNEL_VERSION/extra/me6x00.ko";
+		MOD_INST_AS="/lib/modules/$KERNEL_VERSION/kernel/extra/me6x00.ko";
 		LOCAL_NAME="driver/me6x00.ko";
 	else
 		MOD_INST_AS="/lib/modules/$KERNEL_VERSION/misc/me6x00.o";
@@ -327,170 +477,232 @@ function do_install() {
 	fi
 
 	dialog --yesno \
-"Now we're ready to install everything. This starts with\n\
-copying the following files, if necessary creating\n\
+"Do you want to install the device driver manually?\n\
+We'll copy the following file, if necessary creating\n\
 directories that don't exist:\n\n\
- $LOCAL_NAME     => $MOD_INST_AS\n\
- driver/me6x00_drv.h  => $PREFIX/include/me6x00_drv.h\n\
- lib/libme6x00.so     => $PREFIX/lib/libme6x00.so\n\
- lib/libme6x00.a      => $PREFIX/lib/libme6x00.a\n\
- lib/me6x00.h         => $PREFIX/include/me6x00.h\n\n\
-		Do you want to continue ?" 15 74
+$LOCAL_NAME => $MOD_INST_AS" 12 75
 
-	test $? -eq 0 || exit 0
-
-	# Check that user has root privileges
-
-	if [ `id -u` != "0" ]
+    if [ $? -ne 0 ]
 	then
-		dialog --msgbox \
-"Sorry, you need root privileges to install\n\
- the driver and the library etc. Please\n\
-    become root and then try again.\n" 7 48
-		exit 1;
+		NO_DRIVER_INSTALL=1
+		return
 	fi
 
-	# Do the basic installation (covered by the makefile)
+	make install_driver >> makelog 2>&1
 
-	make install >> makelog 2>&1
 	if [ $? -ne 0 ]
 	then
 		dialog --msgbox \
-"  Sorry, installation failed.\nSee \"makelog\" for the reasons.\n" 7 35;
-		exit 1
+"Sorry, installation of the driver failed.\n\
+See \"makelog\" for the reasons.\n" 7 50;
+    	exit 1
 	fi
-
-	# Find out if user wants to create the device file for the board, but
-	# only if the major device number isn't set to 0.
-
-	if [ $MAJOR -ne 0 ]
-	then
-		dialog --yesno \
-"Do you want to create the device files\n\
-      /dev/me6x00_0\n\
-      /dev/me6x00_1\n\
-      /dev/me6x00_2\n\
-      /dev/me6x00_3\n\n\
-     for the board now?"  12 46
-
-	    if [ $? -eq 0 ]
-		then
-			for i in 0 1 2 3
-			do
-				if [ -e /dev/me6x00_$i ]
-				then 
-					dialog --yesno \
-"A device file /dev/me6x00_$i already exists.\n\
-Delete existing file and replace with a new one?" 7 54;
-					if [ $? -eq 0 ]
-					then
-						rm -f /dev/me6x00_$i
-						mknod /dev/me6x00_$i c $MAJOR $i
-						chmod 666 /dev/me6x00_$i
-					fi
-				else
-					mknod /dev/me6x00_$i c $MAJOR $i
-					chmod 666 /dev/me6x00_$i
-				fi
-			done
-		fi
-
-		# Ask user if the module should be included in /etc/modules.conf (or,
-		# on older installations, in /etc/conf.modules, o, on newer
-		# installations, in /etc/modules.conf.local) and find out if the user
-		# wants to update the modules dependency file
-
-		MODULECONF="/etc/modules.conf";
-		if [ ! -e $MODULECONF -a -e /etc/conf.modules ]
-		then
-			MODULECONF="/etc/conf.modules"
-		fi
-		if [ -e $MODULECONF -a -e /etc/modules.conf.local ]
-		then
-			MODULECONF="/etc/modules.conf.local"
-		fi
-
-		dialog --yesno \
-"  Update $MODULECONF to include the new driver?\n\
- (Old version will be copied to $MODULECONF.bak.)" 7 62
-		test $? -ne 0 || mod_update
-
-	else              # dynamically assigned major device number
-
-		# Try to install the init.d script
-
-		if [    -d /etc/init.d           \
-		 -a -e /lib/lsb/init-functions ]
-		then
-			if [     \(    -e /lib/lsb/install_initd         \
-				        -o -e /usr/lib/lsb/install_initd \)  \
-				 -a \(    -e /lib/lsb/remove_initd          \
-				       -o -e /usr/lib/lsb/remove_initd \) ]
-			then
-				install_lsb
-			elif [ -e /usr/sbin/update-rc.d ]
-			then
-				install_update_rc
-			else
-				dialog --msgbox "\
-Sorry, don't know how to install a script that automatically\n\
-loads the ME6x99 module loaded at boot time and creates the\n\
-device file. Please change the script 'me6x00' in the\n\
-'util' subdirectory to fit your needs and install it\n\
-in the directory for init scripts yourself." 12 70
-			fi
-		fi
-	fi
-
-	update_dep
-
-} # end of do_install()
-
-
-################################################################
-# Removes entries for drivers with the same major number device
-# number from /etc/modules.conf (or, if this is still used,
-# /etc/conf.modules) and adds the ME6X00 driver instead. The old
-# configuration file is saved with the extension .bak
-
-function mod_update() {
-
-cp $MODULECONF $MODULECONF.bak
-
-MAJOR=`grep ME6X00_MAJOR driver/autoconf.h | awk '{print $3}'`
-PATTERN="^[[:space:]]*alias[[:space:]+]char-major-$MAJOR[[:space:]+]"
-LINE=`grep $PATTERN $MODULECONF`
-
-if [ $? -eq 0 ]
-then
-	 grep -v $PATTERN $MODULECONF > /tmp/`basename $MODULECONF`
-	 echo "#$LINE" >> /tmp/`basename $MODULECONF`
-
-	 LINE=`grep "^[[:space:]]*options[[:space:]+]me6x00" /tmp/\`basename $MODULECONF\``;
-	 if [ $? -eq 0 ]
-	 then
-		mv /tmp/`basename $MODULECONF` /tmp/`basename $MODULECONF`2
-		grep -v "$LINE" /tmp/`basename $MODULECONF`2 > /tmp/`basename $MODULECONF`
-		rm -f /tmp/`basename $MODULECONF`2
-		echo "#$LINE" >> /tmp/`basename $MODULECONF`
-	 fi
-
-	 mv /tmp/`basename $MODULECONF` $MODULECONF
-fi
-
-echo "alias char-major-$MAJOR me6x00" >> $MODULECONF
 }
 
 
 ################################################################
 
-function update_dep() {
+function install_device_files()
+{
+	# Find out if user wants to create the device file for the board, but only
+	# if the major device number isn't assigned dynamically (isn't set to 0).
+
+	test $MAJOR -ne 0 || return
+
+	dialog --yesno \
+"Do you want to create the device files\n\n\
+      /dev/me6x00_0\n\
+      /dev/me6x00_1\n\
+      /dev/me6x00_2\n\
+      /dev/me6x00_3\n\n\
+   for the RULBUS interface?"  9 46
+
+    test $? -eq 0 || return
+
+	for i in 0 1 2 3
+	do
+		if [ -e /dev/me6x00_$i ]
+		then 
+			dialog --yesno \
+"A device file /dev/me6x00_$i already exists.\n\
+Delete existing file and replace with a new one?" 7 54;
+
+            if [ $? -eq 0 ]
+			then
+				rm -f /dev/me6x00_$i
+				mknod /dev/me6x00_$i c $MAJOR $i
+				chmod 666 /dev/me6x00_$i
+			fi
+		else
+			mknod /dev/me6x00_$i c $MAJOR $i
+			chmod 666 /dev/me6x00_$i
+		fi
+	done
+}
+
+
+################################################################
+# In the olden times we needed to set up /etc/modules.conf or
+# /etc/modules/conf.modules or /etc/modules.conf.local if the
+# device major number was set staticatlly (i.e. set to non-zero)
+# to get the module loaded at boot time.  In modern times (with
+# /etc/modules) it should be loaded automatically.
+
+function install_modules_conf()
+{
+	if [    -z $MODULECONF \
+		 -o $MODULECONF = "/etc/modules" \
+		 -o $MAJOR -eq 0 ]
+	then
+		return
+	fi
+
+	dialog --yesno \
+"Update $MODULECONF to include the driver? (Old\n\
+version will be saved as $MODULECONF.bak.)" 7 62
+    test $? -eq 0 || return
+
+	cp $MODULECONF $MODULECONF.bak
+
+	PATTERN="^[[:space:]]*alias[[:space:]+]char-major-$MAJOR[[:space:]+]"
+	PATTERN2="^[[:space:]]*pre-install[[:space:]+]me6x00[[:space:]+]"
+
+	LINE=`grep $PATTERN $MODULECONF`
+	if [ $? -eq 0 ]
+	then
+		LINE2=`grep $PATTERN2 $MODULECONF`
+		if [ $? -eq 0 ]
+		then
+			grep -v $PATTERN $MODULECONF | grep -v $PATTERN2 > /tmp/`basename $MODULECONF`
+			echo "#$LINE2" >> /tmp/`basename $MODULECONF`
+			echo "#$LINE" >> /tmp/`basename $MODULECONF`
+		else
+			grep -v $PATTERN $MODULECONF > /tmp/`basename $MODULECONF`
+			echo "#$LINE" >> /tmp/`basename $MODULECONF`
+			fi
+
+		LINE=`grep "^[[:space:]]*options[[:space:]+]me6x00" /tmp/\`basename $MODULECONF\``;
+		if [ $? -eq 0 ]
+		then
+			mv /tmp/`basename $MODULECONF` /tmp/`basename $MODULECONF`2
+			grep -v "$LINE" /tmp/`basename $MODULECONF`2 > /tmp/`basename $MODULECONF`
+			rm -f /tmp/`basename $MODULECONF`2
+			echo "#$LINE" >> /tmp/`basename $MODULECONF`
+		fi
+
+		mv /tmp/`basename $MODULECONF` $MODULECONF
+	fi
+
+	echo "pre-install me6x00 modprobe \"-k\" \"parport\"" >> $MODULECONF
+	echo "alias char-major-$MAJOR me6x00" >> $MODULECONF
+}
+
+
+################################################################
+# In case the major device number is selected dynamically and
+# we're not on a newer system with an /etc/modules file a script
+# can be installed for loading the device driver and creating the
+# devide file at boot time. Ask the user if this should be done
+# and then try to install the script.
+
+function install_init_script()
+{
+	if [ $MAJOR -ne 0 -o $MODULECONF = "/etc/modules" ]
+	then
+		return
+	fi
+
+	dialog --yesno \
+"Should a script be installed to load the driver\n\
+and recreate the device file on reboot?" 7 65
+
+	test $? -eq 0 || return
+
+	# Try to install the init.d script
+
+	if [    -d /etc/init.d \
+		-a -e /lib/lsb/init-functions ]
+	then
+		if [    \(    -e /lib/lsb/install_initd \
+			 -o -e /usr/lib/lsb/install_initd \) \
+			 -a \(    -e /lib/lsb/remove_initd \
+			       -o -e /usr/lib/lsb/remove_initd \) ]
+		then
+			install_lsb
+		elif [ -e /usr/sbin/update-rc.d ]
+		then
+			install_update_rc
+		else
+			dialog --msgbox "\
+Sorry, don't know how to install a script that automatically\n\
+loads the RULBUS module loaded at boot time and creates the\n\
+device file. Please change the script 'me6x00' in the\n\
+'util' subdirectory to fit your needs and install it\n\
+in the directory for init scripts yourself." 12 70
+		fi
+	fi
+}
+
+
+################################################################
+# Updates the modules.dep file for the currently run kernel
+
+function update_dep()
+{
+	if [ -n "$NO_DRIVER_INSTALL" -o -n "$DKMS_INSTALL" ]
+	then
+		return
+	fi
 
 	dialog --yesno \
 "Do you want to update the modules dependency\n\
-file /lib/modules/$KERNEL_VERSION/modules.dep using\n\
-the command 'depmod -a'?" 8 55
+file /lib/modules/$KERNEL_VERSION/modules.dep\n\
+using the command 'depmod'?" 8 55
    test $? -ne 0 || depmod $KERNEL_VERSION -a >/dev/null
+}
+
+
+################################################################
+# Tries to load the module
+
+function load_module()
+{
+	if [ -n "$NO_DRIVER_INSTALL" ]
+	then
+		return
+	fi
+
+	dialog --yesno \
+"Do you want to load the modules into the\n\
+kernel? Make sure no program is using it!" 6 50
+	test $? -eq 0 || return
+
+	# Check if the module is already loaded and try to unload it
+
+	lsmod | grep '^me6x00[ \t]' > /dev/null 2>&1
+	if [ $? -eq 0 ]
+	then
+		rmmod me6x00 >> makelog 2>&1
+		if [ $? -ne 0 ]
+		then
+			dialog --msgbox \
+"Failed to unload running module, so the\n\
+new module could not be loaded. See\n\
+\"makelog\" for the reasons." 8 45
+			return
+		fi
+    fi
+
+	# Now try to load it
+
+	echo "modprobe me6x00" >> makelog
+	modprobe me6x00 >> makelog 2>&1
+	if [ $? -ne 0 ]
+	then
+		dialog --msgbox \
+"Failed to load module into the kernel.\n\
+See \"makelog\" for the reasons." 7 42
+   fi
 }
 
 
@@ -644,19 +856,19 @@ fi
 
 get_kernel_version;
 
-if [    $KV_MAJOR -eq 3                             \
-	 -o \(    $KV_MAJOR -eq 2                       \
-           -a \(    $KV_MINOR -eq 2                 \
-				 -o $KV_MINOR -eq 4                 \
-				 -o $KV_MINOR -e 4 \) \) ]
+if [    $KV_MAJOR -ne 3 \
+	 -a $KV_MAJOR -ne 4 \
+	 -a \(    $KV_MAJOR -ne 2 \
+           -o \( $KV_MINOR -ne 4 -o $KV_MINOR -ne 6 \) \) ]
 then
-
     dialog --yesno \
 "This package is only tested with 2.2, 2.4, 2.6 and 3.x\n\
 kernels. There could be problems with other kernels.\n\n\
            Do you want to continue?" 8 60
     test $? -eq 0 || exit 0
 fi
+
+rm -f makelog > /dev/null 2>&1
 
 if [ ! -e driver/autoconf.h ]
 then
diff --git a/ni6601/INSTALL b/ni6601/INSTALL
--- a/ni6601/INSTALL
+++ b/ni6601/INSTALL
@@ -29,6 +29,34 @@ function get_reply() {
 
 
 ################################################################
+
+function get_module_conf()
+{
+	if [ -e /etc/modules ]
+	then
+		echo "/etc/modules";
+	elif [ -e /etc/modules.conf ]
+	then
+		echo "/etc/modules.conf"
+	elif [ -e /etc/conf.modules ]
+	then
+		echo "/etc/conf.modules"
+	elif [ -e /etc/modules.conf.local ]
+	then
+	    echo "/etc/modules.conf.local"
+	fi
+}
+
+
+################################################################
+
+function get_major()
+{
+	echo `grep NI6601_MAJOR driver/ni6601_autoconf.h | awk '{print $3}'`
+}
+
+
+################################################################
 # Ask the user for the module paramters
 
 function do_setup() {
@@ -46,51 +74,36 @@ README file.\n\n\
 		test $? -eq 0 || exit 0
 	fi
 
-# Ask for the major device number, it must be between 1 and 254 (or 4094
-# for 2.6 and 3.1 kernels) or 0 for a dynamically assigned device number
+	# Ask for the major device number, it must be between 1 and 254 (or 4094
+	# for 2.6 and 3.1 kernels) or 0 for a dynamically assigned device number
 
-	if [ ! IS_NEW_KERNEL ]
+	if [ ! $IS_NEW_KERNEL ]
 	then
-		REPEAT=1;
-		while [ $REPEAT -ne 0 ]
-		do
-			MAJOR=0;
-			REPEAT=0;
-			dialog --inputbox "\
-Select the major device number, pick one between 1 and 254\n\
-and also compare with/usr/src/linux/Documentation/devices.txt.\n\
-Alternatively specify 0 to use a dynamically assigned major\n\
-device number." 12 70 "$MAJOR" 2> /tmp/NI6601_reply
-
-			get_reply MAJOR
-			test -n "$MAJOR" || REPEAT=1
-			test -z `echo $MAJOR | tr -d '[:digit:]'` || REPEAT=1
-			if [ $REPEAT -eq 0 ]
-			then
-				test \( $MAJOR -ge 0 -a $MAJOR -le 254 \) || REPEAT=1
-			fi
-		done
+		MAX_MAJOR=254
 	else
-		REPEAT=1;
-		while [ $REPEAT -ne 0 ]
-		do
-			MAJOR=0;
-			REPEAT=0;
-			dialog --inputbox "\
-Select the major device number, pick one between 1 and 4094\n\
+		MAX_MAJOR=4094
+	fi
+
+	REPEAT=1;
+	while [ $REPEAT -ne 0 ]
+	do
+		MAJOR=0;
+		dialog --inputbox "\
+Select the major device number, pick one between 1 and $MAX_MAJOR\n\
 and also compare with/usr/src/linux/Documentation/devices.txt.\n\
-Alternatively specify 0 to use a dynamically assigned major\n\
+Alternatively, specify 0 to use a dynamically assigned major\n\
 device number." 12 70 "$MAJOR" 2> /tmp/NI6601_reply
 
-			get_reply MAJOR
-			test -n "$MAJOR" || REPEAT=1
-			test -z `echo $MAJOR | tr -d '[:digit:]'` || REPEAT=1
-			if [ $REPEAT -eq 0 ]
-			then
-				test \( $MAJOR -ge 0 -a $MAJOR -le 4094 \) || REPEAT=1
-			fi
-		done
-	fi
+		get_reply MAJOR
+		if [    -n "$MAJOR" \
+			 -a -z "`echo $MAJOR | tr -d '[:digit:]'`" \
+			 -a $MAJOR -ge 0 \
+			 -a $MAJOR -le $MAX_MAJOR ]
+		then
+			echo "Good"
+			REPEAT=0
+		fi
+	done
 
 	# Ask for further compilation options
 
@@ -144,7 +157,7 @@ function make_auto() {
 ################################################################
 # Run setup of parameter until the user is satisfied
 
-function setup_loop() {
+function do_setup_loop() {
     do_setup $1
     while [ $? -ne  0 ]
 	do
@@ -294,43 +307,51 @@ please run the command\n\
 ################################################################
 # Does everything needed for the installation
 
-function do_install() {
-
-# Ask user if he wants to install the library, driver and include files etc.
-
-	PREFIX=`grep NI6601_PREFIX driver/ni6601_autoconf.h | sed 's/[^\"]*//' | tr -d \"`
-	MAJOR=`grep NI6601_MAJOR driver/ni6601_autoconf.h | awk '{print $3}'`;
-	if [ $IS_NEW_KERNEL ]
-	then
-		MOD_INST_AS="/lib/modules/$KERNEL_VERSION/extra/ni6601.ko";
-		LOCAL_NAME="driver/ni6601.ko";
-	else
-		MOD_INST_AS="/lib/modules/$KERNEL_VERSION/misc/ni6601.o";
-		LOCAL_NAME="driver/ni6601.o ";
-	fi
-
-	dialog --yesno \
-"Now we're ready to install the everything. This starts\n\
-with the library, copying the following files and\n\
-creating directories that don't exist:\n\n\
- driver/ni6601_drv.h  => $PREFIX/include/ni6601_drv.h\n\
- lib/ni6601.h         => $PREFIX/include/ni6601.h\n\
- lib/libni6601.a      => $PREFIX/lib/libni6601.a\n\
- lib/libni6601.so     => $PREFIX/lib/libni6601.so\n\n\
-		Do you want to continue ?" 14 65
-
-	test $? -eq 0 || exit 0
-
-	# Check that user has root privileges
+function do_install()
+{
+	# Check that user has the necessary permissions for installation
 
 	if [ `id -u` != "0" ]
 	then
 		dialog --msgbox \
-"Sorry, you need root privileges to install\n\
- the driver and the library etc. Please\n\
-    become root and then try again.\n" 7 48
-		exit 1;
+"For installation you need root privileges.\n\
+Please become root (or run 'INSTALL' with\n\
+'sudo') to continue with the installation.\n" 7 48
+		exit 0;
 	fi
+
+	MAJOR=$(get_major)
+	MODULECONF=$(get_module_conf)
+
+	install_lib
+	install_driver
+	install_device_files
+	install_modules_conf
+	install_init_script
+	update_dep
+	load_module
+}
+
+
+################################################################
+# Installs the library
+
+function install_lib()
+{
+	# Ask user if he wants to install the library
+
+	PREFIX=`grep NI6601_PREFIX driver/ni6601_autoconf.h | sed 's/[^\"]*//' | tr -d \"`
+
+	dialog --yesno \
+"Do you want to install the library? This involves\n\
+copying the following files, if necessary creating\n\
+directories that don't exist:\n\n\
+ driver/ni6601_drv.h  => $PREFIX/include/ni6601_drv.h\n\
+ lib/ni6601.h         => $PREFIX/include/ni6601.h\n\
+ lib/libni6601.a      => $PREFIX/lib/libni6601.a\n\
+ lib/libni6601.so     => $PREFIX/lib/libni6601.so" 14 65
+
+	test $? -eq 0 || return
 
 	# Do the basic installation (covered by the makefile)
 
@@ -338,20 +359,105 @@ creating directories that don't exist:\n\n\
 	if [ $? -ne 0 ]
 	then
 		dialog --msgbox \
-"Sorry, installation of library failed.\n\
+"Sorry, installation of libarary failed.\n\
 See \"makelog\" for the reasons.\n" 7 45;
     	exit 1
 	fi
+}
+
+
+################################################################
+# Installs the kernel module
+
+function install_driver()
+{
+	dkms > /dev/null 2>&1
+	if [ $? -eq 0 ]
+	then
+		dialog --yesno \
+"Do you want to install the device driver using dkms?" 5 60
+        if [ $? -eq 0 ]
+		then
+			install_dkms
+		else
+			install_driver_mech
+		fi
+	else
+		install_driver_mech
+	fi
+}
+
+
+################################################################
+# Installs the kernel module using dkms
+
+function install_dkms()
+{
+	if [ -n "`dkms status -m ni6601 -v 1.0`" ]
+	then
+		dkms uninstall -m ni6601 -v 1.0 -k $KERNEL_VERSION >> makelog 2>&1
+		rm -rf /usr/src/ni6601-1.0 >> makelog 2>&1
+		cp -r driver /usr/src/ni6601-1.0
+	else
+		dkms add driver >> makelog 2>&1
+	fi
+
+	if [ $? -ne 0 ]
+	then
+		dialog --msgbox \
+"Sorry, Failed to add module to dkms.\n\
+See \"makelog\" for the reasons.\n" 7 45;
+        exit 1
+	fi
+
+	dkms build -m ni6601 -v 1.0 -k $KERNEL_VERSION >> makelog 2>&1
+	if [ $? -ne 0 ]
+	then
+"Sorry, Failed to build module with dkms.\n\
+See \"makelog\" for the reasons.\n" 7 45;
+        exit 1
+	fi
+
+	dkms install -m ni6601 -v 1.0 -k $KERNEL_VERSION >> makelog 2>&1
+	if [ $? -ne 0 ]
+	then
+"Sorry, Failed to unstall module with dkms.\n\
+See \"makelog\" for the reasons.\n" 7 45;
+        exit 1
+	fi
+
+	DKMS_INSTALL=1
+}
+
+
+################################################################
+# Installs the kernel module "manually"
+
+function install_driver_mech()
+{
+	if [ $IS_NEW_KERNEL ]
+	then
+		MOD_INST_AS="/lib/modules/$KERNEL_VERSION/kernel/extra/ni6601.ko";
+		LOCAL_NAME="driver/ni6601.ko";
+	else
+		MOD_INST_AS="/lib/modules/$KERNEL_VERSION/misc/ni6601.o";
+		LOCAL_NAME="driver/ni6601.o ";
+	fi
 
 	dialog --yesno \
-"Do you want to install the device driver (you can\n\
-also use dkms instead)? We'll copy the following\n\
-files, if necessary creating directories that\n\
-don't exist:\n\n\
-$LOCAL_NAME => $MOD_INST_AS\n\n\
-		Do you want to continue ?" 14 75
+"Do you want to install the device driver manually?\n\
+We'll copy the following file, if necessary creating\n\
+directories that don't exist:\n\n\
+$LOCAL_NAME => $MOD_INST_AS" 12 75
+
+    if [ $? -ne 0 ]
+	then
+		NO_DRIVER_INSTALL=1
+		return
+	fi
 
 	make install_driver >> makelog 2>&1
+
 	if [ $? -ne 0 ]
 	then
 		dialog --msgbox \
@@ -359,12 +465,18 @@ $LOCAL_NAME => $MOD_INST_AS\n\n\
 See \"makelog\" for the reasons.\n" 7 50;
     	exit 1
 	fi
+}
 
+
+################################################################
+
+function install_device_files()
+{
 	# Find out if user wants to create the device file for the board, but only
-	# if the major device number isn't set to 0.
+	# if the major device number isn't assigned dynamically (isn't set to 0).
 
-	if [ $MAJOR -ne 0 ]
-	then
+	test $MAJOR -ne 0 || return
+
 		dialog --yesno \
 "Do you want to create the device files\n\
       /dev/ni6601_0\n\
@@ -373,97 +485,69 @@ See \"makelog\" for the reasons.\n" 7 50;
       /dev/ni6601_3\n\n\
      for the board now?"  12 46
 
-		if [ $? -eq 0 ]
-		then
-			for i in 0 1 2 3
-			do
-				if [ -e /dev/ni6601_$i ]; then 
-					dialog --yesno \
+    test $? -eq 0 || return
+
+	for i in 0 1 2 3
+	do
+		if [ -e /dev/ni6601_$i ]; then 
+			dialog --yesno \
 "A device file /dev/ni6601_$i already exists.\n\
 Delete existing file and replace with a new one?" 7 54;
-					if [ $? -eq 0 ]
-					then
-						rm -f /dev/ni6601_$i
-						mknod /dev/ni6601_$i c $MAJOR $i
-						chmod 666 /dev/ni6601_$i
-					fi
-				else
-					mknod /dev/ni6601_$i c $MAJOR $i
-					chmod 666 /dev/ni6601_$i
-				fi
-			done
-		fi
 
-		# Ask user if the module should be included in /etc/modules.conf (or,
-		# on older installations, in /etc/conf.modules, or, on newer
-		# installations, in /etc/module.conf.local) and find out if the user
-		# wants to update the modules dependency file
-
-		MODULECONF="/etc/modules.conf";
-		if [ ! -e $MODULECONF -a -e /etc/conf.modules ]
-		then
-			MODULECONF="/etc/conf.modules"
-		fi
-		if [ -e $MODULECONF -a -e /etc/modules.conf.local ]
-		then
-			MODULECONF="/etc/modules.conf.local"
-		fi
-
-		dialog --yesno \
-"  Update $MODULECONF to include the new driver?\n\
- (Old version will be copied to $MODULECONF.bak.)" 7 62
-		test $? -ne 0 || mod_update
-
-	else              # dynamically assigned major device number
-
-		# Try to install the init.d script
-
-		if [    -d /etc/init.d           \
-		 -a -e /lib/lsb/init-functions ]
-		then
-			if [     \(    -e /lib/lsb/install_initd         \
-				        -o -e /usr/lib/lsb/install_initd \)  \
-				 -a \(    -e /lib/lsb/remove_initd          \
-				       -o -e /usr/lib/lsb/remove_initd \) ]
+            if [ $? -eq 0 ]
 			then
-				install_lsb
-			elif [ -e /usr/sbin/update-rc.d ]
-			then
-				install_update_rc
-			else
-				dialog --msgbox "\
-Sorry, don't know how to install a script that automatically\n\
-loads the NI6601 module loaded at boot time and creates the\n\
-device file. Please change the script 'ni6601' in the\n\
-'util' subdirectory to fit your needs and install it\n\
-in the directory for init scripts yourself." 12 70
+				rm -f /dev/ni6601_$i
+				mknod /dev/ni6601_$i c $MAJOR $i
+				chmod 666 /dev/ni6601_$i
 			fi
+		else
+			mknod /dev/ni6601_$i c $MAJOR $i
+			chmod 666 /dev/ni6601_$i
 		fi
-	fi
-
-	update_dep
-
-} # end of do_install()
+	done
+}
 
 
 ################################################################
-# Removes entries for drivers with the same major number device
-# number from /etc/modules.conf (or, if this is still used,
-# /etc/conf.modules) and adds the NI6601 driver instead. The old
-# configuration file is saved with the extension .bak
+# In the olden times we needed to set up /etc/modules.conf or
+# /etc/modules/conf.modules or /etc/modules.conf.local if the
+# device major number was set staticatlly (i.e. set to non-zero)
+# to get the module loaded at boot time.  In modern times (with
+# /etc/modules) it should be loaded autimatically.
 
-function mod_update() {
+function install_modules_conf()
+{
+	if [    -z $MODULECONF \
+		 -o $MODULECONF = "/etc/modules" \
+		 -o $MAJOR -eq 0 ]
+	then
+		return
+	fi
+
+	dialog --yesno \
+"Update $MODULECONF to include the driver? (Old\n\
+version will be saved as $MODULECONF.bak.)" 7 62
+
+    test $? -eq 0 || return
 
 	cp $MODULECONF $MODULECONF.bak
 
-	MAJOR=`grep NI6601_MAJOR driver/ni6601_autoconf.h | awk '{print $3}'`
 	PATTERN="^[[:space:]]*alias[[:space:]+]char-major-$MAJOR[[:space:]+]"
-	LINE=`grep $PATTERN $MODULECONF`
+	PATTERN2="^[[:space:]]*pre-install[[:space:]+]ni6601[[:space:]+]"
 
+	LINE=`grep $PATTERN $MODULECONF`
 	if [ $? -eq 0 ]
 	then
-		grep -v $PATTERN $MODULECONF > /tmp/`basename $MODULECONF`
-		echo "#$LINE" >> /tmp/`basename $MODULECONF`
+		LINE2=`grep $PATTERN2 $MODULECONF`
+		if [ $? -eq 0 ]
+		then
+			grep -v $PATTERN $MODULECONF | grep -v $PATTERN2 > /tmp/`basename $MODULECONF`
+			echo "#$LINE2" >> /tmp/`basename $MODULECONF`
+			echo "#$LINE" >> /tmp/`basename $MODULECONF`
+		else
+			grep -v $PATTERN $MODULECONF > /tmp/`basename $MODULECONF`
+			echo "#$LINE" >> /tmp/`basename $MODULECONF`
+		fi
 
 		LINE=`grep "^[[:space:]]*options[[:space:]+]ni6601" /tmp/\`basename $MODULECONF\``;
 		if [ $? -eq 0 ]
@@ -477,22 +561,121 @@ function mod_update() {
 		mv /tmp/`basename $MODULECONF` $MODULECONF
 	fi
 
+	echo "pre-install ni6601 modprobe \"-k\" \"parport\"" >> $MODULECONF
 	echo "alias char-major-$MAJOR ni6601" >> $MODULECONF
 }
 
 
 ################################################################
+# In case the major device number is selected dynamically and
+# we're not on a newer system with an /etc/modules file a script
+# can be installed for loading the device driver and creating the
+# devide file at boot time. Ask the user if this should be done
+# and then try to install the script.
 
-function update_dep() {
+function install_init_script()
+{
+	if [ $MAJOR -ne 0 -o $MODULECONF = "/etc/modules" ]
+	then
+		return
+	fi
+
+	echo $MAJOR
+	echo $MODULECONF
+	exit
+
+	dialog --yesno \
+"Should a script be installed to load the driver\n\
+and recreate the device file on reboot?" 7 65
+
+	test $? -eq 0 || return
+
+	# Try to install the init.d script
+
+	if [    -d /etc/init.d \
+		-a -e /lib/lsb/init-functions ]
+	then
+		if [    \(    -e /lib/lsb/install_initd \
+			 -o -e /usr/lib/lsb/install_initd \) \
+			 -a \(    -e /lib/lsb/remove_initd \
+			       -o -e /usr/lib/lsb/remove_initd \) ]
+		then
+			install_lsb
+		elif [ -e /usr/sbin/update-rc.d ]
+		then
+			install_update_rc
+		else
+			dialog --msgbox "\
+Sorry, don't know how to install a script that automatically\n\
+loads the RULBUS module loaded at boot time and creates the\n\
+device file. Please change the script 'ni6601' in the\n\
+'util' subdirectory to fit your needs and install it\n\
+in the directory for init scripts yourself." 12 70
+		fi
+	fi
+}
+
+
+################################################################
+# Updates the modules.dep file for the currently run kernel
+
+function update_dep()
+{
+	if [ -n "$NO_DRIVER_INSTALL" -o -n "$DKMS_INSTALL" ]
+	then
+		return
+	fi
 
 	dialog --yesno \
 "Do you want to update the modules dependency\n\
-file /lib/modules/$KERNEL_VERSION/modules.dep using\n\
-the command 'depmod -a'?" 8 55
-
+file /lib/modules/$KERNEL_VERSION/modules.dep\n\
+using the command 'depmod'?" 8 55
    test $? -ne 0 || depmod $KERNEL_VERSION -a >/dev/null
 }
 
+
+################################################################
+# Tries to load the module
+
+function load_module()
+{
+	if [ -n "$NO_DRIVER_INSTALL" ]
+	then
+		return
+	fi
+
+	dialog --yesno \
+"Do you want to load the modules into the\n\
+kernel? Make sure no program is using it!" 6 50
+	test $? -eq 0 || return
+
+	# Check if the module is already loaded and try to unload it
+
+	lsmod | grep '^ni6601[ \t]' > /dev/null 2>&1
+	if [ $? -eq 0 ]
+	then
+		rmmod ni6601 >> makelog 2>&1
+		if [ $? -ne 0 ]
+		then
+			dialog --msgbox \
+"Failed to unload running module, so the\n\
+new module could not be loaded. See\n\
+\"makelog\" for the reasons." 8 45
+			return
+		fi
+    fi
+
+	# Now try to load it
+
+	echo "modprobe ni6601" >> makelog
+	modprobe ni6601 >> makelog 2>&1
+	if [ $? -ne 0 ]
+	then
+		dialog --msgbox \
+"Failed to load module into the kernel.\n\
+See \"makelog\" for the reasons." 7 42
+   fi
+}
 
 ################################################################
 # Chooses either compiling or installing (called at the start
@@ -510,9 +693,9 @@ function pref_comp() {
 
 	get_reply MTYPE
 
-	test $MTYPE != "Setup" || setup_loop 1
+	test $MTYPE != "Setup" || do_setup_loop 1
 
-} # end of pref_comp()
+}
 
 
 ################################################################
@@ -535,7 +718,7 @@ function pref_inst() {
 
 	case $MTYPE in
 		Setup  )
-			setup_loop 1
+			do_setup_loop 1
 			do_compile 0
 			do_install
 			;;
@@ -614,7 +797,7 @@ that kernel sources are at '$KERNEL_DIR'" 6 64;
 	KV_MAJOR=`echo $KERNEL_VERSION | sed 's/^\([0-9]\+\)\..*$/\1/' 2>/dev/null`
 	KV_MINOR=`echo $KERNEL_VERSION | \
               sed 's/^[0-9]\+\.\([0-9]\+\)\..*$/\1/' 2>/dev/null`
-	if [ $KV_MAJOR -lt 2 -o $KV_MINOR -le 4 ]
+	if [ $KV_MAJOR -lt 2 -o \( $KV_MAJOR -eq 2 -a $KV_MINOR -le 4 \) ]
 	then
 		IS_NEW_KERNEL=0;
 	else
@@ -640,13 +823,14 @@ then
 fi
 
 
-# Check if this is a 2.4 kernel
+# Getthe kernel version
 
 get_kernel_version;
 
-if [    $KV_MAJOR -eq 3                                           \
-	 -o \(    $KV_MAJOR -eq 2                                     \
-           -a \( $KV_MINOR -eq 4 -o $KV_MINOR -e 4 \) \) ]
+if [    $KV_MAJOR -ne 3 \
+	 -a $KV_MAJOR -ne 4 \
+	 -a \(    $KV_MAJOR -ne 2 \
+           -o \( $KV_MINOR -ne 4 -a $KV_MINOR -ne 6 \) \) ]
 then
     dialog --yesno \
 "This package is only tested with 2.4, 2.6 and 3.x\n\
@@ -655,9 +839,11 @@ kernels. There cound be problems with other kernels.\n\n\
     test $? -eq 0 || exit 0
 fi
 
+rm -f makelog > /dev/null 2>&1
+
 if [ ! -e driver/ni6601_autoconf.h ]
 then
-   setup_loop 0
+   do_setup_loop 0
    do_compile 0
    do_install
 else
diff --git a/ni6601/driver/Makefile b/ni6601/driver/Makefile
--- a/ni6601/driver/Makefile
+++ b/ni6601/driver/Makefile
@@ -33,13 +33,18 @@ PWD      := $(shell pwd)
 # to the wrong kernel code or may even not exist...
 
 ifneq ($(NI6601_KERNEL_SOURCE),)
-    KERNELDIR := $(NI6601_KERNEL_SOURCE)
+    KERNEL_DIR := $(NI6601_KERNEL_SOURCE)
+endif
+
+ifneq ($(KERNELRELEASE),)
+KERNEL_DIR := /lib/modules/$(KERNELRELEASE)/build
+KERNEL_VER := $(KERNELRELEASE)
 else
-	KERNELDIR := $(shell if [ -d /lib/modules/`uname -r`/build ]; then \
-						     echo "/lib/modules/`uname -r`/build"; \
-						 else \
-							 echo "/usr/src/linux"; \
-						 fi )
+KERNEL_DIR := $(shell if [ -d /lib/modules/`uname -r`/build ]; then \
+					     echo "/lib/modules/`uname -r`/build"; \
+					 else \
+						 echo "/usr/src/linux"; \
+					 fi )
 endif
 
 # If KERNEL_VER isn't set determine it from the the kernel headers (it used
@@ -49,37 +54,34 @@ endif
 # not be found out that way print an error message and bail out.
 
 ifndef KERNEL_VER
-
 KERNEL_VER := $(shell grep 'define[ \t]\+UTS_RELEASE[ \t]\+\"'          \
-                            $(KERNELDIR)/include/generated/utsrelease.h \
+                            $(KERNEL_DIR)/include/generated/utsrelease.h \
 				            2>/dev/null |                               \
 	            	  sed 's/^[^"]\+"\([^"]\+\)".*$$/\1/' 2>/dev/null )
+endif
 
 ifeq ($(KERNEL_VER),)
 	KERNEL_VER := $(shell grep 'define[ \t]\+UTS_RELEASE[ \t]\+\"'        \
-	                            $(KERNELDIR)/include/linux/utsrelease.h   \
+	                            $(KERNEL_DIR)/include/linux/utsrelease.h   \
 					            2>/dev/null |                             \
 		            	  sed 's/^[^"]\+"\([^"]\+\)".*$$/\1/' 2>/dev/null )
 endif
 
 ifeq ($(KERNEL_VER),)
 	KERNEL_VER := $(shell grep 'define[ \t]\+UTS_RELEASE[ \t]\+\"'        \
-	                            $(KERNELDIR)/include/linux/version.h      \
+	                            $(KERNEL_DIR)/include/linux/version.h      \
 					            2>/dev/null |                             \
 		            	  sed 's/^[^"]\+"\([^"]\+\)".*$$/\1/' 2>/dev/null )
 endif
 
 ifeq ($(KERNEL_VER),)
-	KERNEL_VER := $(shell make --quiet -C $(KERNELDIR) kernelrelease 2>/dev/null | grep -v make)
+	KERNEL_VER := $(shell make --quiet -C $(KERNEL_DIR) kernelrelease 2>/dev/null | grep -v make)
 endif
 
-
+ifeq ($(KERNEL_VER),)
 all $(MODULE) install check clean:
-	@if [ -z "$(KERNEL_VER)" ]; then \
-		echo "Error: Can't figure out kernel version under the assumption that the kernel sources are at $(KERNELDIR)"; \
-		exit 2; \
-	fi
-	$(MAKE) $@ KERNEL_VER=$(KERNEL_VER)
+	@echo "Error: Can't figure out kernel version under the assumption that the kernel sources are at $(KERNEL_DIR)"
+	exit 2
 
 else      # if KERNEL_VER is set
 
@@ -87,27 +89,27 @@ else      # if KERNEL_VER is set
 
 ifneq ($(shell echo $(KERNEL_VER) | grep '^\(2\.6\)\|3\.\|4\.' 2>/dev/null),)
 
+ifneq ($(KERNELRELEASE),)    # if invoked from dkms
 obj-m       := $(MODULE)
 ni6601-objs := $(OBJECTS)
+endif
 
 all:
-	$(MAKE) -C $(KERNELDIR) M="$(PWD)"
+	$(MAKE) -C $(KERNEL_DIR) M="$(PWD)"
 
 modules_install install:
-	$(MAKE) -C $(KERNELDIR) M="$(PWD)" modules_install
+	$(MAKE) -C $(KERNEL_DIR) M="$(PWD)" modules_install
 	$(INSTALL) -d $(prefix)/include
 	$(INSTALL) -m 644 ni6601_drv.h $(prefix)/include
 
 clean:
-	$(MAKE) -C $(KERNELDIR) M="$(PWD)" clean
+	$(MAKE) -C $(KERNEL_DIR) M="$(PWD)" clean
 	$(RM) $(RMFLAGS) Module.symvers Module.markers modules.order *~
 
-else
-
-# Otherwise we're dealing with some pre-2.6 kernel (hopefully 2.4)
+else   # pre 2.6 kernels (hopefully 2.4)
 
 HEADERS  = ni6601_drv.h ni6601_autoconf.h
-INCLUDES = -I$(KERNELDIR)/include -I.
+INCLUDES = -I$(KERNEL_DIR)/include -I.
 
 CFLAGS   = -D__KERNEL__ -DMODULE -DLINUX -O2 -Wall -Wstrict-prototypes
 
diff --git a/rulbus/driver/Makefile b/rulbus/driver/Makefile
--- a/rulbus/driver/Makefile
+++ b/rulbus/driver/Makefile
@@ -20,8 +20,7 @@
 
 
 MODULE   := rulbus_epp.o
-SOURCES  := rulbus_epp.c
-HEADERS  := rulbus_epp.h rulbus_epp_autoconf.h
+PWD      := $(shell pwd)
 
 
 # Unless the user set the environment variable RULBUS_EPP_KERNEL_SOURCE
@@ -32,14 +31,19 @@ HEADERS  := rulbus_epp.h rulbus_epp_autoconf.h
 # to the wrong kernel code or may even not exist...
 
 ifneq ($(RULBUS_EPP_KERNEL_SOURCE),)
-    KERNELDIR := $(RULBUS_EPP_KERNEL_SOURCE)
+KERNEL_DIR := $(RULBUS_EPP_KERNEL_SOURCE)
 endif
 
-KERNELDIR ?= $(shell if [ -d /lib/modules/`uname -r`/build ]; then \
-					     echo "/lib/modules/`uname -r`/build"; \
-					 else \
-						 echo "/usr/src/linux"; \
-					 fi )
+ifneq ($(KERNELRELEASE),)
+KERNEL_DIR := /lib/modules/$(KERNELRELEASE)/build
+KERNEL_VER := $(KERNELRELEASE)
+else
+KERNEL_DIR := $(shell if [ -d /lib/modules/`uname -r`/build ]; then \
+					      echo "/lib/modules/`uname -r`/build";     \
+					  else                                          \
+						  echo "/usr/src/linux";                    \
+					  fi )
+endif
 
 # If KERNEL_VER isn't set determine it from the the kernel headers (it used
 # to be defined in linux/version.h but on new systems its' now in its own
@@ -48,38 +52,34 @@ KERNELDIR ?= $(shell if [ -d /lib/modules/`uname -r`/build ]; then \
 # not be found out that way print an error message and bail out.
 
 ifndef KERNEL_VER
-
 KERNEL_VER := $(shell grep 'define[ \t]\+UTS_RELEASE[ \t]\+\"'          \
-                            $(KERNELDIR)/include/linux/utsrelease.h     \
+                            $(KERNEL_DIR)/include/linux/utsrelease.h    \
 				            2>/dev/null |                               \
 	            	  sed 's/^[^"]\+"\([^"]\+\)".*$$/\1/' 2>/dev/null )
+endif
 
 ifeq ($(KERNEL_VER),)
-	KERNEL_VER := $(shell grep 'define[ \t]\+UTS_RELEASE[ \t]\+\"'           \
-	                            $(KERNELDIR)/include/generated/utsrelease.h  \
-					            2>/dev/null |                                \
+	KERNEL_VER := $(shell grep 'define[ \t]\+UTS_RELEASE[ \t]\+\"'            \
+	                            $(KERNEL_DIR)/include/generated/utsrelease.h  \
+					            2>/dev/null |                                 \
 		            	  sed 's/^[^"]\+"\([^"]\+\)".*$$/\1/' 2>/dev/null )
 endif
 
 ifeq ($(KERNEL_VER),)
 	KERNEL_VER := $(shell grep 'define[ \t]\+UTS_RELEASE[ \t]\+\"'          \
-		                        $(KERNELDIR)/include/linux/version.h        \
+		                        $(KERNEL_DIR)/include/linux/version.h       \
 					            2>/dev/null |                               \
 	        	    	  sed 's/^[^"]\+"\([^"]\+\)".*$$/\1/' 2>/dev/null )
 endif
 
-
 ifeq ($(KERNEL_VER),)
-	KERNEL_VER := $(shell make --quiet -C $(KERNELDIR) kernelrelease 2>/dev/null )
+	KERNEL_VER := $(shell make --quiet -C $(KERNEL_DIR) kernelrelease 2>/dev/null )
 endif
 
-
+ifeq ($(KERNEL_VER),)
 all $(MODULE) install check clean:
-	@if [ -z "$(KERNEL_VER)" ]; then \
-		echo "Error: Can't figure out kernel version under the assumption that the kernel sources are at $(KERNELDIR)"; \
-		exit 2; \
-	fi
-	$(MAKE) $@ KERNEL_VER=$(KERNEL_VER)
+	@echo "Error: Can't figure out kernel version under the assumption that the kernel headers (or sources) are at $(KERNEL_DIR)"
+	exit 2
 
 else      # if KERNEL_VER is set
 
@@ -87,27 +87,31 @@ else      # if KERNEL_VER is set
 
 ifneq ($(shell echo $(KERNEL_VER) | grep '^\(2\.6\)\|3\.\|4\.' 2>/dev/null),)
 
-	obj-m := $(MODULE)
+ifneq ($(KERNELRELEASE),)    # if invoked from dkms
+obj-m := $(MODULE)
+endif
 
 all:
-	$(MAKE) -C $(KERNELDIR) M="$(PWD)" modules
+	$(MAKE) -C $(KERNEL_DIR) M=$(PWD) modules
 
 modules_install install:
-	$(MAKE) -C $(KERNELDIR) M="$(PWD)" modules_install
+	$(MAKE) -C $(KERNEL_DIR) M=$(PWD) modules_install
 
 clean:
-	$(MAKE) -C $(KERNELDIR) M="$(PWD)" clean
+	$(MAKE) -C $(KERNEL_DIR) M=$(PWD) clean
 	$(RM) $(RMFLAGS) Module.symvers Module.markers modules.order *~
 
-else
 
-# Otherwise we're dealing with some pre-2.6 kernel (hopefully 2.4)
-# (the -fno-strict-aliasing in CFLAGS is set because of some problems with
-# the 2.4 kernel header files withh gcc 3.3.3 on Debian)
+else   # pre 2.6 kernels (hopefully 2.4)
 
-INCLUDES := -I$(KERNELDIR)/include
+# The -fno-strict-aliasing in CFLAGS is set because of some problems with
+# the 2.4 kernel header files with gcc 3.3.3 on Debian
 
-CFLAGS   := -D__KERNEL__ -DMODULE -DLINUX -O2 -Wall -Wstrict-prototypes  \
+SOURCES  := rulbus_epp.c
+HEADERS  := rulbus_epp.h rulbus_epp_autoconf.h
+INCLUDES := -I$(KERNEL_DIR)/include
+
+CFLAGS   := -D__KERNEL__ -DMODULE -DLINUX -O2 -Wall -Wstrict-prototypes \
             -fno-strict-aliasing
 
 all: $(MODULE)
@@ -128,10 +132,9 @@ ifeq ($(RULBUS_EPP_KERNEL_SOURCE),)
 		fi;                                                           \
 		$(INSTALL) -m 644 $(MODULE) /lib/modules/misc;                \
 	fi
-endif
 
 clean:
 	$(RM) $(RMFLAGS) *.o svn- Module.symvers *~
-
+endif
 endif
 endif
diff --git a/witio_48/INSTALL b/witio_48/INSTALL
--- a/witio_48/INSTALL
+++ b/witio_48/INSTALL
@@ -29,6 +29,34 @@ function get_reply() {
 
 
 ################################################################
+
+function get_module_conf()
+{
+	if [ -e /etc/modules ]
+	then
+		echo "/etc/modules";
+	elif [ -e /etc/modules.conf ]
+	then
+		echo "/etc/modules.conf"
+	elif [ -e /etc/conf.modules ]
+	then
+		echo "/etc/conf.modules"
+	elif [ -e /etc/modules.conf.local ]
+	then
+	    echo "/etc/modules.conf.local"
+	fi
+}
+
+
+################################################################
+
+function get_major()
+{
+	echo `grep WITIO_48_MAJOR driver/autoconf.h | awk '{print $3}'`
+}
+
+
+################################################################
 # Ask the user for the module paramters
 
 function do_setup() {
@@ -151,7 +179,7 @@ You selected the following settings for the driver:\n\n\
           Create 'driver/autoconf.h'?\n" 12 57
 
 	return $?
-} # end of do_setup()
+}
 
 
 ################################################################
@@ -164,13 +192,13 @@ function make_auto() {
 	echo "#define WITIO_48_MAJOR    $MAJOR" >> driver/autoconf.h
 	test $DEBUG -ne 0 || echo "#define WITIO_48_DEBUG" >> driver/autoconf.h
 	echo "#define WITIO_48_PREFIX   \"$PREFIX\"" >> driver/autoconf.h
-} # end of make_auto()
+}
 
 
 ################################################################
 # Run setup of parameter until the user is satisfied
 
-function setup_loop() {
+function do_setup_loop() {
     do_setup $1
     while [ $? -ne  0 ]
 	do
@@ -202,7 +230,7 @@ function do_compile() {
 		 -a ! -e $KERNEL_DIR/include/generated/autoconf.h ]
 	then
 		dialog --msgbox \
-"To create the driver for NI DAQ boards the file\n\
+"To create the driver for the board the file\n\
 $KERNEL_DIR/include/linux/autoconf.h,\n\
 $KERNEL_DIR/include/generated/autoconf.h,\n\
 or /usr/include/linux/autoconf.h, depending on how old\n\
@@ -235,7 +263,7 @@ Unfortunately, the installation can't proceed.\n" 13 62;
 See \"makelog\" for the reasons.\n" 7 45;
     	exit 1;
 	fi
-} # end of do_compile()
+}
 
 
 ################################################################
@@ -318,14 +346,137 @@ please run the command\n\
 ################################################################
 # Does everything needed for the installation
 
-function do_install() {
-	# Ask user if he wants to install the library, driver and include files etc.
+function do_install()
+{
+	# Check that user has the necessary permissions for installation
+
+	if [ `id -u` != "0" ]
+	then
+		dialog --msgbox \
+"For installation you need root privileges.\n\
+Please become root (or run 'INSTALL' with\n\
+'sudo') to continue with the installation.\n" 7 48
+		exit 0;
+	fi
+
+	MAJOR=$(get_major)
+	MODULECONF=$(get_module_conf)
+
+	install_lib
+	install_driver
+	install_device_files
+	install_modules_conf
+	install_init_script
+	update_dep
+	load_module
+}
+
+
+################################################################
+
+function install_lib()
+{
+	# Ask user if he wants to install the library
 
 	PREFIX=`grep WITIO_48_PREFIX driver/autoconf.h | sed 's/[^\"]*//' | tr -d \"`
-	MAJOR=`grep WITIO_48_MAJOR driver/autoconf.h | awk '{print $3}'`;
+
+	dialog --yesno \
+"Do you want to install the library? This involves\n\
+copying the following files, if necessary creating\n\
+directories that don't exist:\n\n\
+ driver/witio_48_drv.h => $PREFIX/include/witio_48_drv.h\n\
+ lib/witio_48.h        => $PREFIX/include/witio_48.h\n\
+ driver/witio_48_drv.h => $PREFIX/include/witio_48_drv.h\n\
+ lib/libwitio_48.a     => $PREFIX/lib/libwitio_48.a\n\
+ lib/libwitio_48.so    => $PREFIX/lib/libwitio_48.so" 13 74
+
+	test $? -eq 0 || return
+
+	# Do the basic installation (covered by the makefile)
+
+	make install_lib >> makelog 2>&1
+	if [ $? -ne 0 ]
+	then
+		dialog --msgbox \
+"Sorry, installation of libarary failed.\n\
+See \"makelog\" for the reasons.\n" 7 45;
+    	exit 1
+	fi
+}
+
+
+################################################################
+# Installs the kernel module
+
+function install_driver()
+{
+	dkms > /dev/null 2>&1
+	if [ $? -eq 0 ]
+	then
+		dialog --yesno \
+"Do you want to install the device driver using dkms?" 5 60
+        if [ $? -eq 0 ]
+		then
+			install_dkms
+		else
+			install_driver_mech
+		fi
+	else
+		install_driver_mech
+	fi
+}
+
+
+################################################################
+# Installs the kernel module using dkms
+
+function install_dkms()
+{
+	if [ -n "`dkms status -m witio_48 -v 1.0`" ]
+	then
+		dkms uninstall -m witio_48 -v 1.0 -k $KERNEL_VERSION >> makelog 2>&1
+		rm -rf /usr/src/witio_48-1.0 >> makelog 2>&1
+		cp -r driver /usr/src/witio_48-1.0
+	else
+		dkms add driver >> makelog 2>&1
+	fi
+
+	if [ $? -ne 0 ]
+	then
+		dialog --msgbox \
+"Sorry, Failed to add module to dkms.\n\
+See \"makelog\" for the reasons.\n" 7 45;
+        exit 1
+	fi
+
+	dkms build -m witio_48 -v 1.0 -k $KERNEL_VERSION >> makelog 2>&1
+	if [ $? -ne 0 ]
+	then
+"Sorry, Failed to build module with dkms.\n\
+See \"makelog\" for the reasons.\n" 7 45;
+        exit 1
+	fi
+
+	dkms install -m witio_48 -v 1.0 -k $KERNEL_VERSION >> makelog 2>&1
+	if [ $? -ne 0 ]
+	then
+"Sorry, Failed to unstall module with dkms.\n\
+See \"makelog\" for the reasons.\n" 7 45;
+        exit 1
+	fi
+
+	DKMS_INSTALL=1
+}
+
+
+################################################################
+# Installs the kernel module "manually"
+
+function install_driver_mech()
+{
 	if [ $IS_NEW_KERNEL ]
 	then
-		MOD_INST_AS="/lib/modules/$KERNEL_VERSION/extra/witio_48.ko";
+		MOD_INST_AS="/lib/modules/$KERNEL_VERSION/kernel/extra/witio_48.ko";
 		LOCAL_NAME="driver/witio_48.ko";
 	else
 		MOD_INST_AS="/lib/modules/$KERNEL_VERSION/misc/witio_48.o";
@@ -333,134 +484,120 @@ function do_install() {
 	fi
 
 	dialog --yesno \
-"Now we're ready to install everything. This starts with\n\
-copying the following files, if necessary creating\n\
+"Do you want to install the device driver manually?\n\
+We'll copy the following file, if necessary creating\n\
 directories that don't exist:\n\n\
- driver/witio_48_drv.h  => $PREFIX/include/witio_48_drv.h\n\
- lib/witio_48.h         => $PREFIX/include/witio_48.h\n\
- lib/libwitio_48.a      => $PREFIX/lib/libwitio_48.a\n\
- lib/libwitio_48.so     => $PREFIX/lib/libwitio_48.so\n\
- $LOCAL_NAME     => $MOD_INST_AS\n\n\
-		Do you want to continue ?" 15 74
+$LOCAL_NAME => $MOD_INST_AS" 12 75
 
-	test $? -eq 0 || exit 0
-
-	# Check that user has root privileges
-
-	if [ `id -u` != "0" ]
+    if [ $? -ne 0 ]
 	then
-		dialog --msgbox \
-"Sorry, you need root privileges to install\n\
- the driver and the library etc. Please\n\
-    become root and then try again.\n" 7 48
-		exit 1;
+		NO_DRIVER_INSTALL=1
+		return
 	fi
 
-	# Do the basic installation (covered by the makefile)
+	make install_driver >> makelog 2>&1
 
-	make install >> makelog 2>&1
 	if [ $? -ne 0 ]
 	then
 		dialog --msgbox \
-"  Sorry, installation failed.\nSee \"makelog\" for the reasons.\n" 7 35;
+"Sorry, installation of the driver failed.\n\
+See \"makelog\" for the reasons.\n" 7 50;
     	exit 1
 	fi
-
-	# Find out if user wants to create the device file for the board, but only
-	# if the major device number isn't set to 0.
-
-	if [ $MAJOR -ne 0 ]
-	then
-		dialog --yesno \
-"Do you want to create the device files\n\
-      /dev/witio_48\n\n\
-     for the board now?"  9 46
-
-		if [ $? -eq 0 ]
-		then
-			if [ -e /dev/witio_48 ]; then 
-				dialog --yesno \
-"A device file /dev/witio_48 already exists.\n\
-Delete existing file and replace with a new one?" 7 54;
-				if [ $? -eq 0 ]
-				then
-					rm -f /dev/witio_48
-					mknod -m 666 /dev/witio_48 c $MAJOR 0
-				fi
-			else
-				mknod -m 666 /dev/witio_48 c $MAJOR 0
-			fi
-		fi
-
-		# Ask user if the module should be included in /etc/modules.conf (or,
-		# on older installations, in /etc/conf.modules, or, on newer
-		# installations, in /etc/modules.conf.local) and find out if the user
-		# wants to update the modules dependency file
-
-		MODULECONF="/etc/modules.conf";
-		if [ ! -e $MODULECONF -a -e /etc/conf.modules ]
-		then
-			MODULECONF="/etc/conf.modules"
-		fi
-		if [ -e $MODULECONF -a -e /etc/modules.conf.local ]
-		then
-			MODULECONF="/etc/modules.conf.local"
-		fi
-
-		dialog --yesno \
-" Update $MODULECONF to include the new driver?\n\
-(Old version will be copied to $MODULECONF.bak.)" 7 62
-		test $? -ne 0 || mod_update
-
-	else              # dynamically assigned major device number
-
-		# Try to install the init.d script
-
-		if [    -d /etc/init.d           \
-		 -a -e /lib/lsb/init-functions ]
-		then
-			if [     \(    -e /lib/lsb/install_initd         \
-				        -o -e /usr/lib/lsb/install_initd \)  \
-				 -a \(    -e /lib/lsb/remove_initd          \
-				       -o -e /usr/lib/lsb/remove_initd \) ]
-			then
-				install_lsb
-			elif [ -e /usr/sbin/update-rc.d ]
-			then
-				install_update_rc
-			else
-				dialog --msgbox "\
-Sorry, don't know how to install a script that automatically\n\
-loads the WITIO_48 module loaded at boot time and creates the\n\
-device file. Please change the script 'witio_48' in the\n\
-'util' subdirectory to fit your needs and install it\n\
-in the directory for init scripts yourself." 12 70
-			fi
-		fi
-	fi
-
-	update_dep
-
-} # end of do_install()
+}
 
 
 ################################################################
-# Removes entries for drivers with the same major number device
-# number from /etc/modules.conf (or, if this is still used,
-# /etc/conf.modules) and adds the WITIO-48 driver instead. The old
-# configuration file is saved with the extension .bak
 
-function mod_update() {
+function install_device_files()
+{
+	# Find out if user wants to create the device file for the board, but only
+	# if the major device number isn't assigned dynamically (isn't set to 0).
+
+	test $MAJOR -ne 0 || return
+
+	dialog --yesno \
+"Do you want to create the device file\n\n\
+        /dev/witio_48\n\n\
+   for the RULBUS interface?"  9 46
+
+    test $? -eq 0 || return
+
+    if [ -e /dev/witio_48 ]
+	then 
+		dialog --yesno \
+"A device file /dev/witio_48 already exists.\n\
+Delete existing file and replace with a new one?" 7 54;
+
+        if [ $? -eq 0 ]
+		then
+			rm -f /dev/witio_48
+			mknod /dev/witio_48 c $MAJOR 0
+			chmod 666 /dev/witio_48
+		fi
+	else
+		mknod /dev/witio_48 c $MAJOR 0
+		chmod 666 /dev/witio_48
+	fi
+}
+
+
+################################################################
+# In the olden times we needed to set up /etc/modules.conf or
+# /etc/modules/conf.modules or /etc/modules.conf.local if the
+# device major number was set staticatlly (i.e. set to non-zero)
+# to get the module loaded at boot time.  And in modern times
+# (with /etc/modules) we can request the same (independent of
+# the major device number) by simply putting the driver's name
+# into /etc/modules.
+
+function install_modules_conf()
+{
+	if [    -z $MODULECONF \
+		 -o \( $MAJOR -eq 0 -a $MODULECONF != "/etc/modules" \) ]
+	then
+		return
+	fi
+
+	if [ $MODULECONF = "/etc/modules" ]
+	then
+		dialog --yesno \
+"Add witio_48 to /etc/modules to have\n\
+the driver loaded on reboots?" 7 50
+        test $? -eq 0 || return
+
+		grep '^[ \t]*witio_48[ \t]*\(#.*\)*$' $MODULECONF 2<&1 > /dev/null;
+		if [ $? -ne 0 ]
+		then
+			cp $MODULECONF $MODULECONF.bak
+			echo "witio_48" >> $MODULECONF
+		fi
+		return
+	fi
+
+	dialog --yesno \
+"Update $MODULECONF to include the driver? (Old\n\
+version will be saved as $MODULECONF.bak.)" 7 62
+    test $? -eq 0 || return
+
 	cp $MODULECONF $MODULECONF.bak
 
-	MAJOR=`grep WITIO_48_MAJOR driver/autoconf.h | awk '{print $3}'`
 	PATTERN="^[[:space:]]*alias[[:space:]+]char-major-$MAJOR[[:space:]+]"
-	LINE=`grep $PATTERN $MODULECONF`
+	PATTERN2="^[[:space:]]*pre-install[[:space:]+]witio_48[[:space:]+]"
 
+	LINE=`grep $PATTERN $MODULECONF`
 	if [ $? -eq 0 ]
 	then
-		grep -v $PATTERN $MODULECONF > /tmp/`basename $MODULECONF`
-		echo "#$LINE" >> /tmp/`basename $MODULECONF`
+		LINE2=`grep $PATTERN2 $MODULECONF`
+		if [ $? -eq 0 ]
+		then
+			grep -v $PATTERN $MODULECONF | grep -v $PATTERN2 > /tmp/`basename $MODULECONF`
+			echo "#$LINE2" >> /tmp/`basename $MODULECONF`
+			echo "#$LINE" >> /tmp/`basename $MODULECONF`
+		else
+			grep -v $PATTERN $MODULECONF > /tmp/`basename $MODULECONF`
+			echo "#$LINE" >> /tmp/`basename $MODULECONF`
+		fi
 
 		LINE=`grep "^[[:space:]]*options[[:space:]+]witio_48" /tmp/\`basename $MODULECONF\``;
 		if [ $? -eq 0 ]
@@ -472,20 +609,118 @@ function mod_update() {
 		fi
 
 		mv /tmp/`basename $MODULECONF` $MODULECONF
-		fi
+	fi
 
-		echo "alias char-major-$MAJOR witio_48" >> $MODULECONF
+	echo "pre-install witio_48 modprobe \"-k\" \"parport\"" >> $MODULECONF
+	echo "alias char-major-$MAJOR witio_48" >> $MODULECONF
 }
 
 
 ################################################################
+# In case the major device number is selected dynamically and
+# we're not on a newer system with an /etc/modules file a script
+# can be installed for loading the device driver and creating the
+# devide file at boot time. Ask the user if this should be done
+# and then try to install the script.
 
-function update_dep() {
+function install_init_script()
+{
+	if [ $MAJOR -ne 0 -o $MODULECONF = "/etc/modules" ]
+	then
+		return
+	fi
+
+	dialog --yesno \
+"Should a script be installed to load the driver\n\
+and recreate the device file on reboot?" 7 65
+
+	test $? -eq 0 || return
+
+	# Try to install the init.d script
+
+	if [    -d /etc/init.d \
+		-a -e /lib/lsb/init-functions ]
+	then
+		if [    \(    -e /lib/lsb/install_initd \
+			 -o -e /usr/lib/lsb/install_initd \) \
+			 -a \(    -e /lib/lsb/remove_initd \
+			       -o -e /usr/lib/lsb/remove_initd \) ]
+		then
+			install_lsb
+		elif [ -e /usr/sbin/update-rc.d ]
+		then
+			install_update_rc
+		else
+			dialog --msgbox "\
+Sorry, don't know how to install a script that automatically\n\
+loads the RULBUS module loaded at boot time and creates the\n\
+device file. Please change the script 'witio_48' in the\n\
+'util' subdirectory to fit your needs and install it\n\
+in the directory for init scripts yourself." 12 70
+		fi
+	fi
+}
+
+
+################################################################
+# Updates the modules.dep file for the currently run kernel
+
+function update_dep()
+{
+	if [ -n "$NO_DRIVER_INSTALL" -o -n "$DKMS_INSTALL" ]
+	then
+		return
+	fi
+
 	dialog --yesno \
 "Do you want to update the modules dependency\n\
 file /lib/modules/$KERNEL_VERSION/modules.dep\n\
-using the command 'depmod -a'?" 8 55
-	test $? -ne 0 || depmod $KERNEL_VERSION -a >/dev/null
+using the command 'depmod'?" 8 55
+   test $? -ne 0 || depmod $KERNEL_VERSION -a >/dev/null
+}
+
+
+################################################################
+# Tries to load the module
+
+function load_module()
+{
+	if [ -n "$NO_DRIVER_INSTALL" ]
+	then
+		return
+	fi
+
+	dialog --yesno \
+"Do you want to load the modules into the\n\
+kernel? Make sure no program is using it!" 6 50
+	test $? -eq 0 || return
+
+	# Check if the module is already loaded and try to unload it
+
+	lsmod | grep '^witio_48[ \t]' > /dev/null 2>&1
+	if [ $? -eq 0 ]
+	then
+		rmmod witio_48 >> makelog 2>&1
+		if [ $? -ne 0 ]
+		then
+			dialog --msgbox \
+"Failed to unload running module, so the\n\
+new module could not be loaded. See\n\
+\"makelog\" for the reasons." 8 45
+			return
+		fi
+    fi
+
+	# Now try to load it
+
+	echo "modprobe witio_48" >> makelog
+	modprobe witio_48 >> makelog 2>&1
+	if [ $? -ne 0 ]
+	then
+		dialog --msgbox \
+"Failed to load module into the kernel.\n\
+See \"makelog\" for the reasons." 7 42
+   fi
 }
 
 
@@ -504,8 +739,8 @@ function pref_comp() {
 
 	get_reply MTYPE
 
-	test $MTYPE != "Setup" || setup_loop 1
-} # end of pref_comp()
+	test $MTYPE != "Setup" || do_setup_loop 1
+}
 
 
 ################################################################
@@ -527,7 +762,7 @@ function pref_inst() {
 
 	case $MTYPE in
 		Setup  )
-			setup_loop 1
+			do_setup_loop 1
 			do_compile 0
 			do_install
 			;;
@@ -632,13 +867,13 @@ then
 fi
 
 
-# Check if this is a 2.4 or 2.6 kernel
+# Get the kernel version
 
 get_kernel_version;
-
-if [    $KV_MAJOR -eq 3                                           \
-	 -o \(    $KV_MAJOR -eq 2                                     \
-           -a \( $KV_MINOR -eq 4 -o $KV_MINOR -e 4 \) \) ]
+if [    $KV_MAJOR -ne 3 \
+	 -a $KV_MAJOR -ne 4 \
+	 -a \(    $KV_MAJOR -ne 2 \
+           -o \( $KV_MINOR -ne 4 -a $KV_MINOR -ne 6 \) \) ]
 then
     dialog --yesno \
 "This package is only tested with 2.4, 2.6 and 3.x\n\
@@ -647,9 +882,11 @@ kernels. There could be problems with other kernels.\n\n\
     test $? -eq 0 || exit 0
 fi
 
+rm -f makelog > /dev/null 2>&1
+
 if [ ! -e driver/autoconf.h ]
 then
-   setup_loop 0
+   do_setup_loop 0
    do_compile 0
    do_install
 else
@@ -667,7 +904,7 @@ else
 fi
 
 dialog --msgbox "\
-Ok, you're hopefully done with creating and \n\
+Ok, you're hopefully done with creating and\n\
 installing the driver and the library." 7 50;
 
 exit 0
diff --git a/witio_48/driver/Makefile b/witio_48/driver/Makefile
--- a/witio_48/driver/Makefile
+++ b/witio_48/driver/Makefile
@@ -20,6 +20,9 @@
 
 
 MODULE   := witio_48.o
+SOURCES  := witio_48_drv.c
+OBJECTS  := $(SOURCES:.c=.o)
+PWD      := $(shell pwd)
 
 # Unless the user set the environment variable WITIO_48_KERNEL_SOURCE
 # assume that we can find out where the kernel sources are (or at least
@@ -29,14 +32,19 @@ MODULE   := witio_48.o
 # to the wrong kernel code or may even not exist...
 
 ifneq ($(WITIO_48_KERNEL_SOURCE),)
-    KERNELDIR := $(WITIO_48_KERNEL_SOURCE)
+KERNEL_DIR := $(WITIO_48_KERNEL_SOURCE)
 endif
 
-KERNELDIR ?= $(shell if [ -d /lib/modules/`uname -r`/build ]; then \
-					     echo "/lib/modules/`uname -r`/build"; \
-					 else \
-						 echo "/usr/src/linux"; \
-					 fi )
+ifneq ($(KERNELRELEASE),)
+KERNEL_DIR := /lib/modules/$(KERNELRELEASE)/build
+KERNEL_VER := $(KERNELRELEASE)
+else
+KERNEL_DIR := $(shell if [ -d /lib/modules/`uname -r`/build ]; then \
+					      echo "/lib/modules/`uname -r`/build";     \
+					  else                                          \
+						  echo "/usr/src/linux";                    \
+					  fi )
+endif
 
 # If KERNEL_VER isn't set determine it from the the kernel headers (it used
 # to be defined in linux/version.h but on new systems its' now in its own
@@ -45,81 +53,60 @@ KERNELDIR ?= $(shell if [ -d /lib/modules/`uname -r`/build ]; then \
 # not be found out that way print an error message and bail out.
 
 ifndef KERNEL_VER
-
 KERNEL_VER := $(shell grep 'define[ \t]\+UTS_RELEASE[ \t]\+\"'            \
-                            $(KERNELDIR)/include/generated/utsrelease.h \
+                            $(KERNEL_DIR)/include/generated/utsrelease.h \
 				            2>/dev/null |                               \
 	            	  sed 's/^[^"]\+"\([^"]\+\)".*$$/\1/' 2>/dev/null )
-
-ifeq ($(KERNEL_VER),)
-	KERNEL_VER := $(shell grep 'define[ \t]\+UTS_RELEASE[ \t]\+\"'            \
-	                            $(KERNELDIR)/include/linux/utsrelease.h     \
-					            2>/dev/null |                               \
-		            	  sed 's/^[^"]\+"\([^"]\+\)".*$$/\1/' 2>/dev/null )
 endif
 
 ifeq ($(KERNEL_VER),)
-	KERNEL_VER := $(shell grep 'define[ \t]\+UTS_RELEASE[ \t]\+\"'            \
-		                        $(KERNELDIR)/include/linux/version.h        \
-					            2>/dev/null |                               \
-	        	    	  sed 's/^[^"]\+"\([^"]\+\)".*$$/\1/' 2>/dev/null )
+KERNEL_VER := $(shell grep 'define[ \t]\+UTS_RELEASE[ \t]\+\"'            \
+                            $(KERNEL_DIR)/include/linux/utsrelease.h     \
+				            2>/dev/null |                               \
+	            	  sed 's/^[^"]\+"\([^"]\+\)".*$$/\1/' 2>/dev/null )
 endif
 
 ifeq ($(KERNEL_VER),)
-	KERNEL_VER := $(shell make --quiet -C $(KERNELDIR) kernelrelease 2>/dev/null | grep -v make)
+KERNEL_VER := $(shell grep 'define[ \t]\+UTS_RELEASE[ \t]\+\"'            \
+	                        $(KERNEL_DIR)/include/linux/version.h        \
+				            2>/dev/null |                               \
+					  sed 's/^[^"]\+"\([^"]\+\)".*$$/\1/' 2>/dev/null )
 endif
 
+ifeq ($(KERNEL_VER),)
+KERNEL_VER := $(shell make --quiet -C $(KERNEL_DIR) kernelrelease 2>/dev/null | grep -v make)
+endif
 
+ifeq ($(KERNEL_VER),)
 all $(MODULE) install check clean:
-	@if [ -z "$(KERNEL_VER)" ]; then \
-		echo "Error: Can't figure out kernel version under the assumption that the kernel sources are at $(KERNELDIR)"; \
-		exit 2; \
-	fi
-	$(MAKE) $@ KERNEL_VER=$(KERNEL_VER)
+	@echo "Error: Can't figure out kernel version under the assumption that the kernel headers (or soures) are at $(KERNEL_DIR)";
+	@exit 2;
 
 else      # if KERNEL_VER is set
 
-# First handle the case that we're building for a 2.6 or 3.x kernel
+# First handle the case that we're building for a 2.6 kernel or newer
 
-ifneq ($(shell echo $(KERNEL_VER) | grep '^\(2\.6\)\|3\.' 2>/dev/null),)
+ifneq ($(shell echo $(KERNEL_VER) | grep '^\(2\.6\)\|3\.\|4\.' 2>/dev/null),)
 
-ifneq ($(KERNELRELEASE),)    # if can use the kernel build system
-	obj-m         := $(MODULE)
-	witio_48-objs := $(OBJECT)
-
-else                         # otherwise make kernel build system available
-
-PWD          := $(shell pwd)
-SOURCE   := witio_48_drv.c
-OBJECT   := $(SOURCE:.c=.o)
-EXTRA_CFLAGS := -I$(PWD)/../include
-export OBJECT
-
-all:
-	$(MAKE) -C $(KERNELDIR) M=$(PWD) EXTRA_CFLAGS=$(EXTRA_CFLAGS)
-
-check:
-	$(MAKE) -C $(KERNELDIR) M="$(PWD)" C=1 EXTRA_CFLAGS="$(EXTRA_CFLAGS)"
-
-install:
-	$(MAKE) -C $(KERNELDIR) M=$(PWD) modules_install
-	$(INSTALL) -d $(prefix)/include
-	$(INSTALL) -m 644 witio_48_drv.h $(prefix)/include
-
-clean:
-	$(MAKE) -C $(KERNELDIR) M=$(PWD) clean
-	$(RM) $(RMFLAGS) Module.symvers Module.markers modules.order *~
-
+ifneq ($(KERNELRELEASE),)    # if invoked from dkms
+obj-m         := $(MODULE)
+witio_48-objs := $(OBJECTS)
 endif
 
-else
+all:
+	$(MAKE) -C $(KERNEL_DIR) M=$(PWD) modules
 
-# Otherwise we're dealing with some pre-2.6 kernel (hopefully 2.4)
+modules_install install:
+	$(MAKE) -C $(KERNEL_DIR) M=$(PWD) modules_install
 
-SOURCE   := witio_48_drv.c
-OBJECT   := $(SOURCE:.c=.o)
+clean:
+	$(MAKE) -C $(KERNEL_DIR) M=$(PWD) clean
+	$(RM) $(RMFLAGS) Module.symvers Module.markers modules.order *~
+
+else   # pre 2.6 kernels (hopefully 2.4)
+
 HEADERS  = witio_48_drv.h autoconf.h
-INCLUDES = -I$(KERNELDIR)/include -I.
+INCLUDES = -I$(KERNEL_DIR)/include
 CFLAGS   = -D__KERNEL__ -DMODULE -DLINUX -O2 -Wall -Wstrict-prototypes
 
 
