Several fixes for module installation

diff --git a/me6x00/utils/me6x00 b/me6x00/utils/me6x00
--- a/me6x00/utils/me6x00
+++ b/me6x00/utils/me6x00
@@ -66,6 +66,7 @@ case "$1" in
 			log_failure_msg "Loading ME6X00 module failed."
 			exit 1
 		fi
+
 		grep 'devfs=only' /proc/cmdline > /dev/null 2>&1
 		if [ $? != 0 ]; then
 			major=`grep me6x00 /proc/devices | awk '{print $1}'`
@@ -76,34 +77,42 @@ case "$1" in
 			nboards=`lspci -n | grep -i '1402:6[01][013][48f]' | wc -l`
 			i=0;
 			while [ $i -lt $nboards ]; do
-				mknod /dev/me6x00_$i c $major $i
-				if [ $? != 0 ]; then
-					log_failure_msg "Creating device files for ME6X00 cards failed."
-					exit 1
+				if [ ! -e /dev/me6x00_$i ]
+				then
+					mknod /dev/me6x00_$i c $major $i
+					if [ $? != 0 ]; then
+						log_failure_msg "Creating device files for ME6X00 cards failed."
+						exit 1
+					fi
+					chmod 666 /dev/me6x00_$i
 				fi
-				chmod 666 /dev/me6x00_$i
 				i=$(($i+1))
 			done
 		fi
-		test "$2" = "restart" || log_success_msg "Starting ME6X00 support."
+		test "$2" = "restart" || log_success_msg "ME6X00 support started."
 		;;
 
 	 stop)
-		grep 'devfs=only' /proc/cmdline > /dev/null 2>&1
-		if [ $? != 0 ]; then
-			for f in /dev/me6x00_*; do
-				rm -f $f
-				if [ $? != 0 ]; then
-					log_failure_msg "Deleting device files for ME6X00 cards failed."
-					exit 1
-				fi
-			done
-		fi
 		rmmod me6x00 > /dev/null 2>&1
 		if [ $? != 0 ]; then
 			log_failure_msg "Unloading ME6X00 module failed."
 			exit 1
 		fi
+
+		grep 'devfs=only' /proc/cmdline > /dev/null 2>&1
+		if [ $? != 0 ]; then
+			for f in /dev/me6x00_*; do
+				if [ -e $f ]
+				then
+					rm -f $f
+					if [ $? != 0 ]; then
+						log_failure_msg "Deleting device files for ME6X00 cards failed."
+						exit 1
+					fi
+				fi
+			done
+		fi
+
 		test "$2" = "restart" || log_success_msg "Stopping ME6X00 support."
 		;;
 
diff --git a/ni6601/utils/ni6601 b/ni6601/utils/ni6601
--- a/ni6601/utils/ni6601
+++ b/ni6601/utils/ni6601
@@ -62,49 +62,67 @@ fi
 case "$1" in
     start)
 		modprobe ni6601 > /dev/null 2>&1
-		if [ $? != 0 ]; then
+		if [ $? != 0 ]
+		then
 			log_failure_msg "Loading NI6601 module failed."
 			exit 1
 		fi
+
 		grep 'devfs=only' /proc/cmdline > /dev/null 2>&1
-		if [ $? != 0 ]; then
+		if [ $? != 0 -]
+		then
 			major=`grep ni6601 /proc/devices | awk '{print $1}'`
-			if [ -z $major ]; then
+			if [ -z $major ]
+			then
 				log_failure_msg "Can't determine major device number for NI6601 cards."
 				exit 1
 			fi
 			nboards=`lspci -n | grep -i '1093:2c60' | wc -l`
 			i=0;
-			while [ $i -lt $nboards ]; do
-				mknod /dev/ni6601_$i c $major $i
-				if [ $? != 0 ]; then
-					log_failure_msg "Creating device files for NI6601 cards failed."
-					exit 1
+			while [ $i -lt $nboards ]
+			do
+				if [ ! -e /dev/ni6601_$i ]
+				then
+					mknod /dev/ni6601_$i c $major $i
+					if [ $? != 0 ]
+					then
+						log_failure_msg "Creating device files for NI6601 cards failed."
+						exit 1
+					fi
+					chmod 666 /dev/ni6601_$i
 				fi
-				chmod 666 /dev/ni6601_$i
 				i=$(($i+1))
 			done
 		fi
-		test "$2" = "restart" || log_success_msg "Starting NI6601 support."
+
+		test "$2" = "restart" || log_success_msg "NI6601 support started."
 		;;
 
 	 stop)
-		grep 'devfs=only' /proc/cmdline > /dev/null 2>&1
-		if [ $? != 0 ]; then
-			for f in /dev/ni6601_*; do
-				rm -f $f
-				if [ $? != 0 ]; then
-					log_failure_msg "Deleting device files for NI6601 cards failed."
-					exit 1
-				fi
-			done
-		fi
 		rmmod ni6601 > /dev/null 2>&1
-		if [ $? != 0 ]; then
+		if [ $? != 0 ]
+		then
 			log_failure_msg "Unloading NI6601 module failed."
 			exit 1
 		fi
-		test "$2" = "restart" || log_success_msg "Stopping NI6601 support."
+
+		grep 'devfs=only' /proc/cmdline > /dev/null 2>&1
+		if [ $? != 0 ]
+		then
+			for f in /dev/ni6601_*; do
+				if [ -e $f ]
+				then
+					rm -f $f
+					if [ $? != 0 ]
+					then
+						log_failure_msg "Deleting device files for NI6601 cards failed."
+						exit 1
+					fi
+				fi
+			done
+		fi
+
+		test "$2" = "restart" || log_success_msg "NI6601 support support."
 		;;
 
 	 restart|reload|force-reload)        # no reason here to differentiate...
@@ -114,7 +132,8 @@ case "$1" in
 
 	 status)
 		grep ni6601 /proc/devices
-		if [ $? = 0 ]; then
+		if [ $? = 0 ]
+		then
 			log_success_msg "NI6601 support is up and running."
 			exit 0
 		else
diff --git a/ni_daq/utils/ni_daq b/ni_daq/utils/ni_daq
--- a/ni_daq/utils/ni_daq
+++ b/ni_daq/utils/ni_daq
@@ -61,15 +61,19 @@ fi
 
 case "$1" in
     start)
-		modprobe ni_daq > /dev/null 2>&1
-		if [ $? != 0 ]; then
+		modprobe pci_e_series > /dev/null 2>&1
+		if [ $? != 0 ]
+		then
 			log_failure_msg "Loading NI_DAQ module failed."
 			exit 1
 		fi
+
 		grep 'devfs=only' /proc/cmdline > /dev/null 2>&1
-		if [ $? != 0 ]; then
+		if [ $? != 0 ]
+		then
 			major=`grep ni_daq /proc/devices | awk '{print $1}'`
-			if [ -z $major ]; then
+			if [ -z $major ]
+			then
 				log_failure_msg "Can't determine major device number for NI_DAQ cards."
 				exit 1
 			fi
@@ -85,13 +89,17 @@ case "$1" in
 			nboards=$(($nboards+`lspci -n | grep -i '1093:18b0' | wc -l`))
 			nboards=$(($nboards+`lspci -n | grep -i '1093:1350' | wc -l`))
 			i=0;
-			while [ $i -lt $nboards -a $i -lt 4 ]; do
-				mknod /dev/pci_e_series_$i c $major $i
-				if [ $? != 0 ]; then
-					log_failure_msg "Creating device files for NI_DAQ cards failed."
-					exit 1
+			while [ $i -lt $nboards -a $i -lt 4 ]
+			do
+				if [ ! -e /dev/pci_e_series_$i ]
+				then
+					mknod /dev/pci_e_series_$i c $major $i
+					if [ $? != 0 ]; then
+						log_failure_msg "Creating device files for NI_DAQ cards failed."
+						exit 1
+					fi
+					chmod 666 /dev/pci_e_series_$i
 				fi
-				chmod 666 /dev/pci_e_series_$i
 				i=$(($i+1))
 			done
 		fi
@@ -99,21 +107,29 @@ case "$1" in
 		;;
 
 	 stop)
-		grep 'devfs=only' /proc/cmdline > /dev/null 2>&1
-		if [ $? != 0 ]; then
-			for f in /dev/pci_e_series_*; do
-				rm -f $f
-				if [ $? != 0 ]; then
-					log_failure_msg "Deleting device files for NI_DAQ cards failed."
-					exit 1
-				fi
-			done
-		fi
 		rmmod ni_daq > /dev/null 2>&1
-		if [ $? != 0 ]; then
+		if [ $? != 0 ]
+		then
 			log_failure_msg "Unloading NI_DAQ module failed."
 			exit 1
 		fi
+
+		grep 'devfs=only' /proc/cmdline > /dev/null 2>&1
+		if [ $? != 0 ]
+		then
+			for f in /dev/pci_e_series_*
+			do
+				if [ -e $f ]
+				then
+					rm -f $f
+					if [ $? != 0 ]; then
+						log_failure_msg "Deleting device files for NI_DAQ cards failed."
+						exit 1
+					fi
+				fi
+			done
+		fi
+
 		test "$2" = "restart" || log_success_msg "Stopping NI_DAQ support."
 		;;
 
@@ -124,7 +140,8 @@ case "$1" in
 
 	 status)
 		grep ni_daq /proc/devices
-		if [ $? = 0 ]; then
+		if [ $? = 0 ]
+		then
 			log_success_msg "NI_DAQ support is up and running."
 			exit 0
 		else
@@ -132,6 +149,7 @@ case "$1" in
 			exit 3
 		fi
 		;;
+
     *)
 		echo "Usage: $0 {start|stop|restart|force-reload|reload|status}"
 		exit 1
diff --git a/rulbus/utils/rulbus_epp b/rulbus/utils/rulbus_epp
--- a/rulbus/utils/rulbus_epp
+++ b/rulbus/utils/rulbus_epp
@@ -69,13 +69,15 @@ case "$1" in
 				exit 1
 			fi
 		fi
+
 		modprobe rulbus_epp > /dev/null 2>&1
 		if [ $? != 0 ]; then
 			log_failure_msg "Loading Rulbus EPP module failed."
 			exit 1
 		fi
+
 		grep 'devfs=only' /proc/cmdline > /dev/null 2>&1
-		if [ $? != 0 ]; then
+		if [ $? != 0 -a ! -e /dev/rulbus_epp ]; then
 			major=`grep rulbus_epp /proc/devices | awk '{print $1}'`
 			if [ -z $major ]; then
 				log_failure_msg "Can't determine major device number for Rulbus EPP interface."
@@ -88,24 +90,25 @@ case "$1" in
 			fi
 			chmod 666 /dev/rulbus_epp
 		fi
-		test "$2" = "restart" || log_success_msg "Rulbus EPP support."
+		test "$2" = "restart" || log_success_msg "Rulbus EPP support started."
 		;;
 
 	 stop)
-		grep 'devfs=only' /proc/cmdline > /dev/null 2>&1
+		rmmod rulbus_epp > /dev/null 2>&1
 		if [ $? != 0 ]; then
+			log_failure_msg "Unloading Rulbus EPP module failed."
+			exit 1
+		fi
+
+		grep 'devfs=only' /proc/cmdline > /dev/null 2>&1
+		if [ $? != 0 -a -e /dev/rulbus_epp ]; then
 			rm -f /dev/rulbus_epp
 			if [ $? != 0 ]; then
 				log_failure_msg "Deleting device files for Rulbus EPP interface failed."
 				exit 1
 			fi
 		fi
-		rmmod rulbus_epp > /dev/null 2>&1
-		if [ $? != 0 ]; then
-			log_failure_msg "Unloading Rulbus EPP module failed."
-			exit 1
-		fi
-		test "$2" = "restart" || log_success_msg "Stopping Rulbus EPP support."
+		test "$2" = "restart" || log_success_msg "Rulbus EPP support stopped."
 		;;
 
 	 restart|reload|force-reload)        # no reason here to differentiate...
@@ -114,7 +117,7 @@ case "$1" in
 		;;
 
 	 status)
-		grep ni_daq /proc/devices
+		grep rulbus_epp /proc/devices
 		if [ $? = 0 ]; then
 			log_success_msg "Rulbus EPP support is up and running."
 			exit 0
