*** empty log message ***
git-svn-id: file:///usr/local/svn/fsc2@6282 934aee4a-8510-0410-ae50-ec5b2ea4bb86

diff --git a/trunk/fsc2/ni6601/utils/ni6601 b/trunk/fsc2/ni6601/utils/ni6601
--- a/trunk/fsc2/ni6601/utils/ni6601
+++ b/trunk/fsc2/ni6601/utils/ni6601
@@ -69,33 +69,39 @@ case "$1" in
 			log_failure_msg "Loading NI6601 module failed."
 			exit 1
 		fi
-		major=`grep ni6601 /proc/devices | awk '{print $1}'`
+		grep 'devfs=only' /proc/cmdline > /dev/null 2>&1
 		if [ $? != 0 ]; then
-			log_failure_msg "Can't determine major device number for NI6601 cards."
-			exit 1
-		fi
-		nboards=`grep '1093:2c60' /proc/pci | wc -l`
-		i=0;
-		while [ $i -lt $nboards ]; do
-			mknod /dev/ni6601_$i c $major $i
+			major=`grep ni6601 /proc/devices | awk '{print $1}'`
 			if [ $? != 0 ]; then
-				log_failure_msg "Creating device files for NI6601 cards failed."
+				log_failure_msg "Can't determine major device number for NI6601 cards."
 				exit 1
 			fi
-			chmod 666 /dev/ni6601_$i
-			i=$(($i+1))
-		done
+			nboards=`grep '1093:2c60' /proc/pci | wc -l`
+			i=0;
+			while [ $i -lt $nboards ]; do
+				mknod /dev/ni6601_$i c $major $i
+				if [ $? != 0 ]; then
+					log_failure_msg "Creating device files for NI6601 cards failed."
+					exit 1
+				fi
+				chmod 666 /dev/ni6601_$i
+				i=$(($i+1))
+			done
+		fi
 		test "$2" = "restart" || log_success_msg "Starting NI6601 support."
 		;;
 
 	 stop)
-		for f in /dev/ni6601_*; do
-			rm -f $f
-			if [ $? != 0 ]; then
-				log_failure_msg "Deleting device files for NI6601 cards failed."
-				exit 1
-			fi
-		done
+		grep 'devfs=only' /proc/cmdline > /dev/null 2>&1
+		if [ $? != 0 ]; then
+			for f in /dev/ni6601_*; do
+				rm -f $f
+				if [ $? != 0 ]; then
+					log_failure_msg "Deleting device files for NI6601 cards failed."
+					exit 1
+				fi
+			done
+		fi
 		rmmod ni6601 > /dev/null 2>&1
 		if [ $? != 0 ]; then
 			log_failure_msg "Unloading NI6601 module failed."
