Added support for 2.6 kernels.
git-svn-id: file:///usr/local/svn/fsc2@7870 934aee4a-8510-0410-ae50-ec5b2ea4bb86

diff --git a/trunk/fsc2/ni_daq/driver/Makefile b/trunk/fsc2/ni_daq/driver/Makefile
--- a/trunk/fsc2/ni_daq/driver/Makefile
+++ b/trunk/fsc2/ni_daq/driver/Makefile
@@ -22,20 +22,81 @@
 # To contact the author send email to:  jt@toerring.de
 
 
+MODULE  := ni_daq.o
+
+
+# Unless the user set the environment variable NI6601_KERNEL_SOURCE
+# assume that we can find out where the kernel sources are (or at least
+# the kernel headers) from the 'build' symbolic link in the module
+# directory of the currently running kernel. Only if this doesn't exist
+# use '/usr/src/linux/' as a last resort - but it's not unlikely to point
+# to the wrong kernel code or may even not exist...
+
 ifneq ($(NI_DAQ_KERNEL_SOURCE),)
-    KERNEL_INC := $(NI_DAQ_KERNEL_SOURCE)
-else
-	KERNEL_SRC := $(shell if [ -d /lib/modules/`uname -r`/build ]; then \
-							 echo "/lib/modules/`uname -r`/build"; \
-						 else \
-							 echo "/usr/src/linux"; \
-						 fi )
+    KERNELDIR := $(NI_DAQ_KERNEL_SOURCE)
 endif
 
+KERNELDIR ?= $(shell if [ -d /lib/modules/`uname -r`/build ]; then \
+					     echo "/lib/modules/`uname -r`/build"; \
+					 else \
+						 echo "/usr/src/linux"; \
+					 fi )
 
-MODULE = ni_daq.o
-SOURCES = $(shell ls pci_e_series/*.c daq_stc/*.c)
-INCLUDES := -I$(KERNEL_SRC)/include -I.
+# If KERNEL_VER isn't set determine it from the the kernel source directory
+# and then call make again with KERNEL_VER now being set. If KERNEL_VER
+# couldn't be found out that way give up and print an error message
+
+ifndef KERNEL_VER
+
+KERNEL_VER := $(shell grep UTS_RELEASE $(KERNELDIR)/include/linux/version.h \
+				      2>/dev/null | \
+				      sed 's/^[^"]\{1,\}"\([0-9\.]\{1,\}\).*$$/\1/' \
+					  2>/dev/null)
+
+all $(MODULE) install clean:
+	@if [ -z "$(KERNEL_VER)" ]; then \
+		echo "Error: Can't figure out kernel version under the assumption that the kernel sources are at $(KERNELDIR)"; \
+		exit 2; \
+	fi
+	$(MAKE) $@ KERNEL_VER=$(KERNEL_VER)
+
+else      # if KERNEL_VER is set
+
+# First handle the case that we're building for a 2.6 kernel
+
+ifeq ($(findstring 2.6,$(KERNEL_VER)),2.6)
+
+ifneq ($(KERNELRELEASE),)    # if can use the kernel build system
+	obj-m       := $(MODULE)
+	ni_daq-objs := $(OBJECTS)
+
+else                         # otherwise make kernel build system available
+
+PWD          := $(shell pwd)
+SOURCES      := $(shell ls pci_e_series/*.c daq_stc/*.c)
+OBJECTS      := $(SOURCES:.c=.o)
+EXTRA_CFLAGS := -I$(PWD)/include -I$(PWD)/../include
+export OBJECTS
+
+all:
+	$(MAKE) -C $(KERNELDIR) M="$(PWD)" EXTRA_CFLAGS="$(EXTRA_CFLAGS)"
+
+install:
+	$(MAKE) -C $(KERNELDIR) M="$(PWD)" modules_install
+
+clean:
+	$(MAKE) -C $(KERNELDIR) M="$(PWD)" clean
+	$(RM) $(RMFLAGS) *~
+
+endif
+
+else
+
+# Otherwise we're dealing with some pre-2.6 kernel (hopefully 2.4)
+
+
+SOURCES  := $(shell ls pci_e_series/*.c daq_stc/*.c)
+INCLUDES := -I$(KERNELDIR)/include -I.
 CC       := gcc
 CFLAGS   := -D__KERNEL__ -DMODULE -DLINUX -O2 -Wall -Wstrict-prototypes -s
 
@@ -59,16 +120,16 @@ $(MODULE): $(SOURCES:.c=.o)
 
 install:
 ifeq ($(NI_DAQ_KERNEL_SOURCE),)
-	if [ -d /lib/modules/`uname -r` ]; then                        \
-		if [ ! -d /lib/modules/`uname -r`/misc ]; then             \
-			$(INSTALL) -m 755 -d /lib/modules/`uname -r`/misc;     \
-		fi;                                                        \
-		$(INSTALL) -m 644 $(MODULE) /lib/modules/`uname -r`/misc;  \
-	else                                                           \
-		if [ ! -d /lib/modules/misc ]; then                        \
-			$(INSTALL) -m 755 -d /lib/modules/misc;                \
-		fi;                                                        \
-		$(INSTALL) -m 644 $(MODULE) /lib/modules/misc;             \
+	if [ -d /lib/modules/$KERNEL_VER ]; then                        \
+		if [ ! -d /lib/modules/$KERNEL_VER/misc ]; then             \
+			$(INSTALL) -m 755 -d /lib/modules/$KERNEL_VER/misc;     \
+		fi;                                                         \
+		$(INSTALL) -m 644 $(MODULE) /lib/modules/$KERNEL_VER/misc;  \
+	else                                                            \
+		if [ ! -d /lib/modules/misc ]; then                         \
+			$(INSTALL) -m 755 -d /lib/modules/misc;                 \
+		fi;                                                         \
+		$(INSTALL) -m 644 $(MODULE) /lib/modules/misc;              \
 	fi
 endif
 
@@ -80,4 +141,7 @@ cleanup:
 
 clean:
 	$(MAKE) cleanup
-	$(RM) $(RMFLAGS) ni_daq.o include/autoconf.h
+	$(RM) $(RMFLAGS) ni_daq.o
+
+endif
+endif
